; ======================================================
; Minimal passive FTP control-channel client for Sprinter DSS Network Kit.
; Data-channel commands will be added after the control flow is stable.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 5000
FTP_RECV_TIMEOUT	EQU 10000
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
USER_SIZE		EQU 48
PASS_SIZE		EQU 64
CMD_SIZE		EQU 128
RECV_SIZE		EQU 384
LINE_SIZE		EQU 112
NO_HANDLE		EQU 0xFF

		DEVICE NOSLOT64K

		INCLUDE "macro.inc"
		INCLUDE "dss.inc"

		MODULE MAIN

		ORG 0x8080
EXE_HEADER
		DB "EXE"
		DB EXE_VERSION
		DW 0x0080
		DW 0
		DW 0
		DW 0
		DW 0
		DW 0
		DW START
		DW START
		DW STACK_TOP
		DS 106, 0

		ORG 0x8100
@STACK_TOP

START
		CALL	CLEAR_BSS
		CALL	ISA.ISA_RESET
		CALL	WCOMMON.INIT_VMODE
		PRINTLN MSG_START

		CALL	PARSE_CMD_LINE
		JP	C,USAGE

		CALL	WIFI.UART_FIND
		JP	C,NO_WIFI
		LD	A,(ISA.ISA_SLOT)
		ADD	A,'1'
		LD	(MSG_SLOT_NO),A
		PRINTLN	MSG_WIFI_FOUND

		CALL	NETCFG.LOAD
		CALL	NETCFG.APPLY_UART_BAUD
		CALL	WIFI.UART_INIT
		PRINTLN MSG_UART_READY

		LD	HL,CMD_AT
		CALL	SEND_CMD_RECOVER
		LD	HL,CMD_ECHO_OFF
		CALL	SEND_CMD
		CALL	WCOMMON.SETUP_UART_FLOW
		AND	A
		JP	NZ,NET_ERROR_EXIT
		LD	HL,CMD_CIPMUX_0
		CALL	SEND_CMD

		PRINT MSG_CONNECTING
		PRINT HOST_BUFF
		PRINT MSG_COLON
		PRINT PORT_BUFF
		PRINT WCOMMON.LINE_END

		LD	HL,HOST_BUFF
		LD	DE,PORT_BUFF
		CALL	TCP.OPEN
		JP	C,NET_ERROR_EXIT
		LD	A,1
		LD	(CONTROL_OPEN),A

		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT

		PRINTLN MSG_LOGIN
		LD	DE,FTP_USER_PREFIX
		LD	IX,USER_BUFF
		CALL	BUILD_FTP_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_USER_REPLY
		JP	C,FTP_ERROR_EXIT

		LD	A,(REPLY_FIRST)
		CP	'3'
		JR	NZ,.NO_PASS
		LD	DE,FTP_PASS_PREFIX
		LD	IX,PASS_BUFF
		CALL	BUILD_FTP_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT

.NO_PASS
		PRINTLN MSG_BINARY
		LD	DE,FTP_TYPE_I
		CALL	BUILD_SIMPLE_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT

		LD	DE,FTP_QUIT
		CALL	BUILD_SIMPLE_COMMAND
		CALL	SEND_CONTROL
		CALL	RECV_CONTROL_REPLY_IGNORE

		CALL	CLEANUP_TCP
		PRINTLN MSG_DONE
		LD	B,0
		JP	WCOMMON.EXIT

USAGE
		PRINTLN MSG_USAGE
		LD	B,1
		JP	WCOMMON.EXIT

NO_WIFI
		PRINTLN MSG_WIFI_NOT_FOUND
		LD	B,2
		JP	WCOMMON.EXIT

NET_ERROR_EXIT
		PUSH	AF
		CALL	CLEANUP_TCP
		POP	AF
		ADD	A,'0'
		LD	(MSG_NET_ERROR_NO),A
		PRINTLN MSG_NET_ERROR
		LD	B,3
		JP	WCOMMON.EXIT

FTP_ERROR_EXIT
		CALL	CLEANUP_TCP
		PRINT MSG_FTP_ERROR
		LD	A,(REPLY_CODE_1)
		CALL	PUT_CHAR
		LD	A,(REPLY_CODE_2)
		CALL	PUT_CHAR
		LD	A,(REPLY_CODE_3)
		CALL	PUT_CHAR
		PRINT WCOMMON.LINE_END
		LD	B,4
		JP	WCOMMON.EXIT

; ------------------------------------------------------
; Parse: FTP.EXE host[:port] [user [password]]
; ------------------------------------------------------
PARSE_CMD_LINE
		LD	HL,DEFAULT_PORT
		LD	DE,PORT_BUFF
		CALL	COPY_ASCIIZ_DE
		LD	HL,DEFAULT_USER
		LD	DE,USER_BUFF
		CALL	COPY_ASCIIZ_DE
		LD	HL,DEFAULT_PASS
		LD	DE,PASS_BUFF
		CALL	COPY_ASCIIZ_DE

		LD	HL,0x8080
		LD	A,(HL)
		AND	A
		JR	Z,.ERR
		LD	B,A
		INC	HL
		CALL	SKIP_SPACES
		JR	C,.ERR
		LD	DE,HOST_BUFF
		LD	C,HOST_SIZE-1
		CALL	COPY_ARG
		JR	C,.ERR
		CALL	SPLIT_HOST_PORT

		CALL	SKIP_SPACES
		JR	C,.OK
		LD	DE,USER_BUFF
		LD	C,USER_SIZE-1
		CALL	COPY_ARG
		JR	C,.ERR

		CALL	SKIP_SPACES
		JR	C,.OK
		LD	DE,PASS_BUFF
		LD	C,PASS_SIZE-1
		CALL	COPY_ARG
		JR	C,.ERR
.OK
		LD	A,(HOST_BUFF)
		AND	A
		RET	NZ
.ERR
		SCF
		RET

SKIP_SPACES
		LD	A,B
		AND	A
		JR	Z,.ERR
.NEXT
		LD	A,(HL)
		CP	' '
		RET	NZ
		INC	HL
		DJNZ	.NEXT
.ERR
		SCF
		RET

COPY_ARG
		XOR	A
		LD	(ARG_LEN),A
.NEXT
		LD	A,B
		AND	A
		JR	Z,.END
		LD	A,(HL)
		CP	' '
		JR	Z,.END
		LD	A,(ARG_LEN)
		CP	C
		JR	NC,.ERR
		LD	A,(HL)
		LD	(DE),A
		INC	HL
		INC	DE
		DEC	B
		LD	A,(ARG_LEN)
		INC	A
		LD	(ARG_LEN),A
		JR	.NEXT
.END
		XOR	A
		LD	(DE),A
		LD	A,(ARG_LEN)
		AND	A
		RET	NZ
.ERR
		SCF
		RET

SPLIT_HOST_PORT
		LD	HL,HOST_BUFF
.NEXT
		LD	A,(HL)
		AND	A
		RET	Z
		CP	':'
		JR	Z,.FOUND
		INC	HL
		JR	.NEXT
.FOUND
		XOR	A
		LD	(HL),A
		INC	HL
		LD	DE,PORT_BUFF
		LD	C,PORT_SIZE-1
		CALL	COPY_ASCIIZ_LIMIT
		RET

COPY_ASCIIZ_LIMIT
		LD	A,(HL)
		AND	A
		JR	Z,.END
		LD	A,C
		AND	A
		JR	Z,.END
		LD	A,(HL)
		LD	(DE),A
		INC	HL
		INC	DE
		DEC	C
		JR	COPY_ASCIIZ_LIMIT
.END
		XOR	A
		LD	(DE),A
		RET

COPY_ASCIIZ_DE
		LD	A,(HL)
		LD	(DE),A
		AND	A
		RET	Z
		INC	HL
		INC	DE
		JR	COPY_ASCIIZ_DE

; ------------------------------------------------------
; FTP control channel.
; ------------------------------------------------------
BUILD_FTP_COMMAND
		LD	HL,CMD_BUFF
		CALL	APPEND_STR
		CALL	APPEND_IX_STR
		LD	DE,CMD_CRLF
		CALL	APPEND_STR
		JR	SET_CMD_LEN

BUILD_SIMPLE_COMMAND
		LD	HL,CMD_BUFF
		CALL	APPEND_STR
SET_CMD_LEN
		LD	DE,CMD_BUFF
		OR	A
		SBC	HL,DE
		LD	(CMD_LEN),HL
		RET

SEND_CONTROL
		LD	HL,CMD_BUFF
		LD	BC,(CMD_LEN)
		JP	TCP.SEND_BUFFER

RECV_CONTROL_REPLY_IGNORE
		CALL	RECV_CONTROL_REPLY
		RET

RECV_CONTROL_REPLY
		XOR	A
		LD	(REPLY_DONE),A
		LD	(REPLY_FIRST),A
		LD	(REPLY_CODE_1),A
		LD	(REPLY_CODE_2),A
		LD	(REPLY_CODE_3),A
		LD	(LINE_LEN),A
.READ
		LD	HL,RECV_BUFFER
		LD	BC,RECV_SIZE
		LD	DE,FTP_RECV_TIMEOUT
		CALL	TCP.RECEIVE
		RET	C
		LD	A,B
		OR	C
		JR	Z,.READ
		LD	HL,RECV_BUFFER
		CALL	FEED_CONTROL_BYTES
		LD	A,(REPLY_DONE)
		AND	A
		JR	Z,.READ
		XOR	A
		RET

FEED_CONTROL_BYTES
		LD	A,B
		OR	C
		RET	Z
.NEXT
		LD	A,(HL)
		INC	HL
		DEC	BC
		CP	13
		JR	Z,.CHECK
		CP	10
		JR	Z,.LINE
		PUSH	BC,HL
		CALL	APPEND_LINE_CHAR
		POP	HL,BC
		JR	.CHECK
.LINE
		PUSH	BC,HL
		CALL	FINISH_LINE
		POP	HL,BC
.CHECK
		LD	A,(REPLY_DONE)
		AND	A
		RET	NZ
		LD	A,B
		OR	C
		JR	NZ,.NEXT
		RET

APPEND_LINE_CHAR
		LD	C,A
		LD	A,(LINE_LEN)
		CP	LINE_SIZE-1
		RET	NC
		LD	E,A
		LD	D,0
		LD	HL,LINE_BUFF
		ADD	HL,DE
		LD	(HL),C
		LD	A,(LINE_LEN)
		INC	A
		LD	(LINE_LEN),A
		RET

FINISH_LINE
		LD	A,(LINE_LEN)
		AND	A
		JR	Z,.RESET
		LD	E,A
		LD	D,0
		LD	HL,LINE_BUFF
		ADD	HL,DE
		XOR	A
		LD	(HL),A
		PRINTLN	LINE_BUFF
		CALL	PARSE_REPLY_LINE
.RESET
		XOR	A
		LD	(LINE_LEN),A
		RET

PARSE_REPLY_LINE
		LD	HL,LINE_BUFF
		CALL	IS_DIGIT_AT_HL
		RET	C
		LD	A,(HL)
		LD	(REPLY_CODE_1),A
		LD	(REPLY_FIRST),A
		INC	HL
		CALL	IS_DIGIT_AT_HL
		RET	C
		LD	A,(HL)
		LD	(REPLY_CODE_2),A
		INC	HL
		CALL	IS_DIGIT_AT_HL
		RET	C
		LD	A,(HL)
		LD	(REPLY_CODE_3),A
		INC	HL
		LD	A,(HL)
		CP	' '
		RET	NZ
		LD	A,1
		LD	(REPLY_DONE),A
		RET

IS_DIGIT_AT_HL
		LD	A,(HL)
		CP	'0'
		JR	C,.ERR
		CP	'9'+1
		JR	NC,.ERR
		OR	A
		RET
.ERR
		SCF
		RET

CHECK_REPLY_POSITIVE
		LD	A,(REPLY_FIRST)
		CP	'2'
		RET	Z
		CP	'3'
		RET	Z
		SCF
		RET

CHECK_USER_REPLY
		LD	A,(REPLY_FIRST)
		CP	'2'
		RET	Z
		CP	'3'
		RET	Z
		SCF
		RET

CLEANUP_TCP
		LD	A,(CONTROL_OPEN)
		AND	A
		RET	Z
		CALL	TCP.CLOSE
		XOR	A
		LD	(CONTROL_OPEN),A
		RET

SEND_CMD
		LD	DE,WIFI.RS_BUFF
		LD	BC,DEFAULT_TIMEOUT
		CALL	WIFI.UART_TX_CMD
		AND	A
		RET	Z
		ADD	A,'0'
		LD	(MSG_ERROR_NO),A
		PRINTLN MSG_COMM_ERROR
		LD	B,3
		JP	WCOMMON.EXIT

SEND_CMD_IGNORE
		LD	DE,WIFI.RS_BUFF
		LD	BC,DEFAULT_TIMEOUT
		CALL	WIFI.UART_TX_CMD
		RET

SEND_CMD_RECOVER
		PUSH	HL
		LD	DE,WIFI.RS_BUFF
		LD	BC,DEFAULT_TIMEOUT
		CALL	WIFI.UART_TX_CMD
		AND	A
		JR	Z,.OK
		PRINTLN MSG_RESETTING_ESP
		CALL	WIFI.ESP_RESET
		CALL	WIFI.UART_SET_DEFAULT_DIVISOR
		CALL	WIFI.UART_INIT
		POP	HL
		JP	SEND_CMD
.OK
		POP	HL
		RET

APPEND_STR
		LD	A,(DE)
		AND	A
		RET	Z
		LD	(HL),A
		INC	HL
		INC	DE
		JR	APPEND_STR

APPEND_IX_STR
		LD	A,(IX+0)
		AND	A
		RET	Z
		LD	(HL),A
		INC	HL
		INC	IX
		JR	APPEND_IX_STR

PUT_CHAR
		PUSH	BC,HL
		LD	C,DSS_PUTCHAR
		RST	DSS
		POP	HL,BC
		RET

CLEAR_BSS
		LD	HL,FTP_BSS_BASE
		LD	DE,FTP_BSS_BASE+1
		LD	BC,FTP_BSS_END-FTP_BSS_BASE-1
		XOR	A
		LD	(HL),A
		LDIR
		RET

MSG_START
		DB "FTP - FTP control smoke test for SprinterESP",0
MSG_USAGE
		DB "Usage: FTP.EXE host[:port] [user [password]]",0
MSG_WIFI_FOUND
		DB "Sprinter-WiFi found in ISA#"
MSG_SLOT_NO
		DB "n slot.",0
MSG_WIFI_NOT_FOUND
		DB "Sprinter-WiFi not found!",0
MSG_UART_READY
		DB "UART initialized.",0
MSG_RESETTING_ESP
		DB "ESP did not answer, resetting module.",0
MSG_CONNECTING
		DB "Connecting to ",0
MSG_COLON
		DB ":",0
MSG_LOGIN
		DB "Logging in.",0
MSG_BINARY
		DB "Setting binary transfer mode.",0
MSG_DONE
		DB "FTP done.",0
MSG_COMM_ERROR
		DB "ESP communication error #"
MSG_ERROR_NO
		DB "n!",0
MSG_NET_ERROR
		DB "Network/ESP error #"
MSG_NET_ERROR_NO
		DB "n!",0
MSG_FTP_ERROR
		DB "FTP server returned error: ",0

CMD_AT
		DB "AT",13,10,0
CMD_ECHO_OFF
		DB "ATE0",13,10,0
CMD_CIPMUX_0
		DB "AT+CIPMUX=0",13,10,0
CMD_CRLF
		DB 13,10,0

DEFAULT_PORT
		DB "21",0
DEFAULT_USER
		DB "anonymous",0
DEFAULT_PASS
		DB "sprinter@example",0
FTP_USER_PREFIX
		DB "USER ",0
FTP_PASS_PREFIX
		DB "PASS ",0
FTP_TYPE_I
		DB "TYPE I",13,10,0
FTP_QUIT
		DB "QUIT",13,10,0

ARG_LEN
		DB 0
CONTROL_OPEN
			DB 0
CMD_LEN
			DW 0
LINE_LEN
		DB 0
REPLY_DONE
		DB 0
REPLY_FIRST
		DB 0
REPLY_CODE_1
		DB 0
REPLY_CODE_2
		DB 0
REPLY_CODE_3
		DB 0

		ENDMODULE

		INCLUDE "netcfg_lib.asm"
		INCLUDE "wcommon.asm"
		INCLUDE "dss_error.asm"
		INCLUDE "isa.asm"
		INCLUDE "esp_tcp.asm"
		INCLUDE "esplib.asm"

		MODULE MAIN

FTP_BSS_BASE	EQU NETCFG.NETCFG_BSS_END
HOST_BUFF	EQU FTP_BSS_BASE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
USER_BUFF	EQU PORT_BUFF + PORT_SIZE
PASS_BUFF	EQU USER_BUFF + USER_SIZE
CMD_BUFF	EQU PASS_BUFF + PASS_SIZE
RECV_BUFFER	EQU CMD_BUFF + CMD_SIZE
LINE_BUFF	EQU RECV_BUFFER + RECV_SIZE
FTP_BSS_END	EQU LINE_BUFF + LINE_SIZE

		ENDMODULE

		END MAIN.START
