; ======================================================
; Minimal passive FTP client for Sprinter DSS Network Kit.
; Logs in, opens PASV data link and prints a LIST directory listing.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 5000
FTP_RECV_TIMEOUT	EQU 10000
FTP_DATA_TIMEOUT	EQU 20000
FTP_FINAL_TIMEOUT	EQU 2500
CONTROL_LINK		EQU 0
DATA_LINK		EQU 1
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
USER_SIZE		EQU 48
PASS_SIZE		EQU 64
CMD_SIZE		EQU 128
RECV_SIZE		EQU 384
LINE_SIZE		EQU 112
NO_HANDLE		EQU 0xFF
DATA_CLOSED_LEN		EQU 8

		DEVICE NOSLOT64K

		INCLUDE "macro.inc"
		INCLUDE "dss.inc"

		MODULE MAIN

		; Full 512-byte DSS EXE header. Long command lines are written
		; at 0x8080, so these tools must not use the compact header.
		ORG 0x7F00
EXE_HEADER
		DB "EXE"
		DB EXE_VERSION
		DW 0x0200
		DW 0
		DW 0
		DW 0
		DW 0
		DW 0
		DW START
		DW START
		DW STACK_TOP
		DS 490, 0

		ORG 0x8100
@STACK_TOP

START
		CALL	CLEAR_BSS
		CALL	ISA.ISA_RESET
		CALL	WCOMMON.INIT_VMODE
		PRINTLN MSG_START

		CALL	PARSE_CMD_LINE
		JP	C,USAGE

		CALL	WIFI.UART_FIND
		JP	C,NO_WIFI
		LD	A,(ISA.ISA_SLOT)
		ADD	A,'1'
		LD	(MSG_SLOT_NO),A
		PRINTLN	MSG_WIFI_FOUND

		CALL	NETCFG.LOAD
		CALL	NETCFG.APPLY_UART_BAUD
		CALL	WIFI.UART_INIT
		PRINTLN MSG_UART_READY

		LD	HL,CMD_AT
		CALL	SEND_CMD_RECOVER
		LD	HL,CMD_ECHO_OFF
		CALL	SEND_CMD
		CALL	WCOMMON.SETUP_UART_FLOW
		AND	A
		JP	NZ,NET_ERROR_EXIT
		LD	HL,CMD_CIPMUX_1
		CALL	SEND_CMD

		PRINT MSG_CONNECTING
		PRINT HOST_BUFF
		PRINT MSG_COLON
		PRINT PORT_BUFF
		PRINT WCOMMON.LINE_END

		LD	A,CONTROL_LINK
		LD	HL,HOST_BUFF
		LD	DE,PORT_BUFF
		CALL	TCP.OPEN_LINK
		JP	C,NET_ERROR_EXIT
		LD	A,1
		LD	(CONTROL_OPEN),A

		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT

		PRINTLN MSG_LOGIN
		LD	DE,FTP_USER_PREFIX
		LD	IX,USER_BUFF
		CALL	BUILD_FTP_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_USER_REPLY
		JP	C,FTP_ERROR_EXIT

		LD	A,(REPLY_FIRST)
		CP	'3'
		JR	NZ,.NO_PASS
		LD	DE,FTP_PASS_PREFIX
		LD	IX,PASS_BUFF
		CALL	BUILD_FTP_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT

.NO_PASS
		PRINTLN MSG_BINARY
		LD	DE,FTP_TYPE_I
		CALL	BUILD_SIMPLE_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT

		PRINTLN MSG_PASV
		LD	DE,FTP_PASV
		CALL	BUILD_SIMPLE_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	PARSE_PASV_ENDPOINT
		JP	C,FTP_ERROR_EXIT
		PRINT MSG_PASV_ENDPOINT
		PRINT PASV_HOST_BUFF
		PRINT MSG_COLON
		PRINT PASV_PORT_BUFF
		PRINT WCOMMON.LINE_END

		PRINT MSG_OPEN_DATA
		PRINT PASV_HOST_BUFF
		PRINT MSG_COLON
		PRINT PASV_PORT_BUFF
		PRINT WCOMMON.LINE_END
		LD	A,DATA_LINK
		LD	HL,PASV_HOST_BUFF
		LD	DE,PASV_PORT_BUFF
		CALL	TCP.OPEN_LINK
		JP	C,NET_ERROR_EXIT
		LD	A,1
		LD	(DATA_OPEN),A

		PRINTLN MSG_LIST
		LD	DE,FTP_LIST
		CALL	BUILD_SIMPLE_COMMAND
		CALL	SEND_CONTROL
		JP	C,NET_ERROR_EXIT
		CALL	RECV_CONTROL_REPLY
		JP	C,NET_ERROR_EXIT
		CALL	CHECK_LIST_PRELIM_REPLY
		JP	C,FTP_ERROR_EXIT
		PRINTLN MSG_LISTING
		CALL	RECV_DATA_LIST
		JP	C,NET_ERROR_EXIT
		LD	A,(FINAL_REPLY_SEEN)
		AND	A
		JR	NZ,.CHECK_FINAL_REPLY
		CALL	RECV_CONTROL_REPLY_OPTIONAL
		JR	C,.LIST_DONE
.CHECK_FINAL_REPLY
		CALL	CHECK_REPLY_POSITIVE
		JP	C,FTP_ERROR_EXIT
.LIST_DONE

		LD	DE,FTP_QUIT
		CALL	BUILD_SIMPLE_COMMAND
		CALL	SEND_CONTROL
		CALL	RECV_CONTROL_REPLY_IGNORE

		CALL	CLEANUP_TCP
		PRINTLN MSG_DONE
		LD	B,0
		JP	WCOMMON.EXIT

USAGE
		PRINTLN MSG_USAGE
		LD	B,1
		JP	WCOMMON.EXIT

NO_WIFI
		PRINTLN MSG_WIFI_NOT_FOUND
		LD	B,2
		JP	WCOMMON.EXIT

NET_ERROR_EXIT
		PUSH	AF
		CALL	CLEANUP_TCP
		POP	AF
		ADD	A,'0'
		LD	(MSG_NET_ERROR_NO),A
		PRINTLN MSG_NET_ERROR
		LD	B,3
		JP	WCOMMON.EXIT

FTP_ERROR_EXIT
		CALL	CLEANUP_TCP
		PRINT MSG_FTP_ERROR
		LD	A,(REPLY_CODE_1)
		CALL	PUT_CHAR
		LD	A,(REPLY_CODE_2)
		CALL	PUT_CHAR
		LD	A,(REPLY_CODE_3)
		CALL	PUT_CHAR
		PRINT WCOMMON.LINE_END
		LD	B,4
		JP	WCOMMON.EXIT

; ------------------------------------------------------
; Parse: FTP.EXE host[:port] [user [password]]
; ------------------------------------------------------
PARSE_CMD_LINE
		LD	HL,DEFAULT_PORT
		LD	DE,PORT_BUFF
		CALL	COPY_ASCIIZ_DE
		LD	HL,DEFAULT_USER
		LD	DE,USER_BUFF
		CALL	COPY_ASCIIZ_DE
		LD	HL,DEFAULT_PASS
		LD	DE,PASS_BUFF
		CALL	COPY_ASCIIZ_DE

		LD	HL,0x8080
		LD	A,(HL)
		AND	A
		JR	Z,.ERR
		LD	B,A
		INC	HL
		CALL	SKIP_SPACES
		JR	C,.ERR
		LD	DE,HOST_BUFF
		LD	C,HOST_SIZE-1
		CALL	COPY_ARG
		JR	C,.ERR
		CALL	SPLIT_HOST_PORT

		CALL	SKIP_SPACES
		JR	C,.OK
		LD	DE,USER_BUFF
		LD	C,USER_SIZE-1
		CALL	COPY_ARG
		JR	C,.ERR

		CALL	SKIP_SPACES
		JR	C,.OK
		LD	DE,PASS_BUFF
		LD	C,PASS_SIZE-1
		CALL	COPY_ARG
		JR	C,.ERR
.OK
		LD	A,(HOST_BUFF)
		AND	A
		RET	NZ
.ERR
		SCF
		RET

SKIP_SPACES
		LD	A,B
		AND	A
		JR	Z,.ERR
.NEXT
		LD	A,(HL)
		CP	' '
		RET	NZ
		INC	HL
		DJNZ	.NEXT
.ERR
		SCF
		RET

COPY_ARG
		XOR	A
		LD	(ARG_LEN),A
.NEXT
		LD	A,B
		AND	A
		JR	Z,.END
		LD	A,(HL)
		CP	' '
		JR	Z,.END
		LD	A,(ARG_LEN)
		CP	C
		JR	NC,.ERR
		LD	A,(HL)
		LD	(DE),A
		INC	HL
		INC	DE
		DEC	B
		LD	A,(ARG_LEN)
		INC	A
		LD	(ARG_LEN),A
		JR	.NEXT
.END
		XOR	A
		LD	(DE),A
		LD	A,(ARG_LEN)
		AND	A
		RET	NZ
.ERR
		SCF
		RET

SPLIT_HOST_PORT
		LD	HL,HOST_BUFF
.NEXT
		LD	A,(HL)
		AND	A
		RET	Z
		CP	':'
		JR	Z,.FOUND
		INC	HL
		JR	.NEXT
.FOUND
		XOR	A
		LD	(HL),A
		INC	HL
		LD	DE,PORT_BUFF
		LD	C,PORT_SIZE-1
		CALL	COPY_ASCIIZ_LIMIT
		RET

COPY_ASCIIZ_LIMIT
		LD	A,(HL)
		AND	A
		JR	Z,.END
		LD	A,C
		AND	A
		JR	Z,.END
		LD	A,(HL)
		LD	(DE),A
		INC	HL
		INC	DE
		DEC	C
		JR	COPY_ASCIIZ_LIMIT
.END
		XOR	A
		LD	(DE),A
		RET

COPY_ASCIIZ_DE
		LD	A,(HL)
		LD	(DE),A
		AND	A
		RET	Z
		INC	HL
		INC	DE
		JR	COPY_ASCIIZ_DE

; ------------------------------------------------------
; FTP control channel.
; ------------------------------------------------------
BUILD_FTP_COMMAND
		LD	HL,CMD_BUFF
		CALL	APPEND_STR
		CALL	APPEND_IX_STR
		LD	DE,CMD_CRLF
		CALL	APPEND_STR
		JR	SET_CMD_LEN

BUILD_SIMPLE_COMMAND
		LD	HL,CMD_BUFF
		CALL	APPEND_STR
SET_CMD_LEN
		LD	DE,CMD_BUFF
		OR	A
		SBC	HL,DE
		LD	(CMD_LEN),HL
		RET

SEND_CONTROL
		LD	HL,CMD_BUFF
		LD	BC,(CMD_LEN)
		LD	A,CONTROL_LINK
		JP	TCP.SEND_BUFFER_LINK_NO_WAIT

RECV_CONTROL_REPLY_IGNORE
		CALL	RECV_CONTROL_REPLY
		RET

RECV_CONTROL_REPLY
		LD	DE,FTP_RECV_TIMEOUT
		JP	RECV_CONTROL_REPLY_TIMEOUT

RECV_CONTROL_REPLY_OPTIONAL
		LD	DE,FTP_FINAL_TIMEOUT
		JP	RECV_CONTROL_REPLY_TIMEOUT

RECV_CONTROL_REPLY_TIMEOUT
		LD	(CONTROL_TIMEOUT),DE
		CALL	RESET_REPLY_STATE
.READ
		LD	HL,RECV_BUFFER
		LD	BC,RECV_SIZE
		LD	DE,(CONTROL_TIMEOUT)
		CALL	TCP.RECEIVE_ANY_LINK
		RET	C
		LD	A,B
		OR	C
		JR	Z,.READ
		LD	A,(TCP.LAST_IPD_LINK)
		CP	CONTROL_LINK
		JR	Z,.CONTROL
		CP	DATA_LINK
		JR	NZ,.READ
		; Data link bytes arrived before the control reply.
		; Print them as listing data instead of dropping them and
		; flag that we have already started the listing transfer.
		LD	A,1
		LD	(DATA_BYTES_SEEN),A
		LD	HL,RECV_BUFFER
		CALL	PRINT_BUFFER
		JR	.READ
.CONTROL
		LD	HL,RECV_BUFFER
		CALL	FEED_CONTROL_BYTES
		LD	A,(REPLY_DONE)
		AND	A
		JR	Z,.READ
		XOR	A
		RET

RESET_REPLY_STATE
		XOR	A
		LD	(REPLY_DONE),A
		LD	(REPLY_FIRST),A
		LD	(REPLY_CODE_1),A
		LD	(REPLY_CODE_2),A
		LD	(REPLY_CODE_3),A
		LD	(LINE_LEN),A
		RET

FEED_CONTROL_BYTES
		LD	A,B
		OR	C
		RET	Z
.NEXT
		LD	A,(HL)
		INC	HL
		DEC	BC
		CP	13
		JR	Z,.CHECK
		CP	10
		JR	Z,.LINE
		PUSH	BC,HL
		CALL	APPEND_LINE_CHAR
		POP	HL,BC
		JR	.CHECK
.LINE
		PUSH	BC,HL
		CALL	FINISH_LINE
		POP	HL,BC
.CHECK
		LD	A,(REPLY_DONE)
		AND	A
		RET	NZ
		LD	A,B
		OR	C
		JR	NZ,.NEXT
		RET

APPEND_LINE_CHAR
		LD	C,A
		LD	A,(LINE_LEN)
		CP	LINE_SIZE-1
		RET	NC
		LD	E,A
		LD	D,0
		LD	HL,LINE_BUFF
		ADD	HL,DE
		LD	(HL),C
		LD	A,(LINE_LEN)
		INC	A
		LD	(LINE_LEN),A
		RET

FINISH_LINE
		LD	A,(LINE_LEN)
		AND	A
		JR	Z,.RESET
		LD	E,A
		LD	D,0
		LD	HL,LINE_BUFF
		ADD	HL,DE
		XOR	A
		LD	(HL),A
		PRINTLN	LINE_BUFF
		CALL	PARSE_REPLY_LINE
.RESET
		XOR	A
		LD	(LINE_LEN),A
		RET

PARSE_REPLY_LINE
		LD	HL,LINE_BUFF
		CALL	IS_DIGIT_AT_HL
		RET	C
		LD	A,(HL)
		LD	(REPLY_CODE_1),A
		LD	(REPLY_FIRST),A
		INC	HL
		CALL	IS_DIGIT_AT_HL
		RET	C
		LD	A,(HL)
		LD	(REPLY_CODE_2),A
		INC	HL
		CALL	IS_DIGIT_AT_HL
		RET	C
		LD	A,(HL)
		LD	(REPLY_CODE_3),A
		INC	HL
		LD	A,(HL)
		CP	' '
		RET	NZ
		LD	A,1
		LD	(REPLY_DONE),A
		RET

IS_DIGIT_AT_HL
		LD	A,(HL)
		CP	'0'
		JR	C,.ERR
		CP	'9'+1
		JR	NC,.ERR
		OR	A
		RET
.ERR
		SCF
		RET

CHECK_REPLY_POSITIVE
		LD	A,(REPLY_FIRST)
		CP	'2'
		RET	Z
		CP	'3'
		RET	Z
		SCF
		RET

CHECK_USER_REPLY
		LD	A,(REPLY_FIRST)
		CP	'2'
		RET	Z
		CP	'3'
		RET	Z
		SCF
		RET

PARSE_PASV_ENDPOINT
		LD	A,(REPLY_CODE_1)
		CP	'2'
		JR	NZ,.ERR
		LD	A,(REPLY_CODE_2)
		CP	'2'
		JR	NZ,.ERR
		LD	A,(REPLY_CODE_3)
		CP	'7'
		JR	NZ,.ERR
		LD	HL,LINE_BUFF
.FIND_OPEN
		LD	A,(HL)
		AND	A
		JR	Z,.ERR
		CP	'('
		JR	Z,.PARSE
		INC	HL
		JR	.FIND_OPEN
.PARSE
		INC	HL
		CALL	PARSE_DEC_BYTE
		JR	C,.ERR
		LD	(PASV_H1),A
		CALL	EXPECT_COMMA
		JR	C,.ERR
		CALL	PARSE_DEC_BYTE
		JR	C,.ERR
		LD	(PASV_H2),A
		CALL	EXPECT_COMMA
		JR	C,.ERR
		CALL	PARSE_DEC_BYTE
		JR	C,.ERR
		LD	(PASV_H3),A
		CALL	EXPECT_COMMA
		JR	C,.ERR
		CALL	PARSE_DEC_BYTE
		JR	C,.ERR
		LD	(PASV_H4),A
		CALL	EXPECT_COMMA
		JR	C,.ERR
		CALL	PARSE_DEC_BYTE
		JR	C,.ERR
		LD	(PASV_P1),A
		CALL	EXPECT_COMMA
		JR	C,.ERR
		CALL	PARSE_DEC_BYTE
		JR	C,.ERR
		LD	(PASV_P2),A
		CALL	BUILD_PASV_ENDPOINT
		XOR	A
		RET
.ERR
		SCF
		RET

EXPECT_COMMA
		LD	A,(HL)
		CP	','
		JR	NZ,.ERR
		INC	HL
		XOR	A
		RET
.ERR
		SCF
		RET

PARSE_DEC_BYTE
		LD	E,0
		LD	B,0
.NEXT
		LD	A,(HL)
		CP	'0'
		JR	C,.DONE
		CP	'9'+1
		JR	NC,.DONE
		SUB	'0'
		LD	C,A
		LD	A,E
		ADD	A,A
		LD	D,A
		ADD	A,A
		ADD	A,A
		ADD	A,D
		ADD	A,C
		LD	E,A
		INC	HL
		INC	B
		JR	.NEXT
.DONE
		LD	A,B
		AND	A
		JR	Z,.ERR
		LD	A,E
		OR	A
		RET
.ERR
		SCF
		RET

CHECK_LIST_PRELIM_REPLY
		LD	A,(REPLY_FIRST)
		CP	'1'
		RET	Z
		CP	'2'
		RET	Z
		SCF
		RET

RECV_DATA_LIST
		XOR	A
		LD	(FINAL_REPLY_SEEN),A
		LD	(DATA_CLOSE_SEEN),A
		; Note: DATA_BYTES_SEEN may already be set by an earlier
		; RECV_CONTROL_REPLY that received data-link bytes while
		; waiting for the 150 reply. Don't clear it here.
		CALL	RESET_REPLY_STATE
.READ
		LD	HL,RECV_BUFFER
		LD	BC,RECV_SIZE
		LD	DE,FTP_DATA_TIMEOUT
		CALL	TCP.RECEIVE_ANY_LINK
		JR	C,.ERROR
		LD	A,B
		OR	C
		JR	Z,.READ
		LD	A,(TCP.LAST_IPD_LINK)
		CP	DATA_LINK
		JR	Z,.DATA
		CP	CONTROL_LINK
		JR	NZ,.READ
		; Treat any control IPD as evidence the transfer is in
		; progress. Without this, a UART overrun that corrupts the
		; link-id digit ('1' lost in "+IPD,1,N:") would silently
		; route directory bytes through FEED_CONTROL_BYTES and
		; leave DATA_BYTES_SEEN=0, producing a false #4 timeout.
		LD	A,1
		LD	(DATA_BYTES_SEEN),A
		LD	HL,RECV_BUFFER
		CALL	FEED_CONTROL_BYTES
		LD	A,(REPLY_DONE)
		AND	A
		JR	Z,.READ
		LD	A,1
		LD	(FINAL_REPLY_SEEN),A
		JR	.READ
.DATA
		LD	A,1
		LD	(DATA_BYTES_SEEN),A
		LD	HL,RECV_BUFFER
		CALL	PRINT_BUFFER
		LD	A,(DATA_CLOSE_SEEN)
		AND	A
		JR	NZ,.CLOSED
		JR	.READ
.ERROR
		; If we already received any IPD bytes, treat any error
		; (timeout, parser desync from UART overrun, link closed)
		; as end-of-listing. TCP can't recover lost bytes anyway,
		; so report what we have rather than failing the whole run.
		PUSH	AF
		LD	A,(DATA_BYTES_SEEN)
		OR	A
		JR	Z,.NO_DATA_YET
		POP	AF
		JR	.CLOSED
.NO_DATA_YET
		POP	AF
		CP	RES_NOT_CONN
		JR	Z,.CLOSED
		SCF
		RET
.CLOSED
		XOR	A
		LD	(DATA_OPEN),A
		; Reset TCP receive state. Without this a partially-read
		; +IPD chunk leaves PAYLOAD_LEFT non-zero and LAST_IPD_LINK
		; pointing at the data link, so the next RECEIVE_ANY_LINK
		; (e.g. waiting for the QUIT reply) skips WAIT_IPD_HEADER
		; and consumes "0,SEND OK\r\n+IPD,0,N:..." as stale payload,
		; printing it through PRINT_BUFFER.
		LD	HL,0
		LD	(TCP.PAYLOAD_LEFT),HL
		LD	A,0xFF
		LD	(TCP.LAST_IPD_LINK),A
		PRINT WCOMMON.LINE_END
		RET

; ------------------------------------------------------
; Print FTP data as console text.
; In: HL - data, BC - length.
; ------------------------------------------------------
PRINT_BUFFER
		LD	A,B
		OR	C
		RET	Z
		CALL	MATCH_DATA_CLOSED_TOKEN
		JR	C,.NOT_CLOSED
		LD	A,1
		LD	(DATA_CLOSE_SEEN),A
		RET
.NOT_CLOSED
		LD	A,(HL)
		INC	HL
		DEC	BC
		CP	13
		JR	Z,PRINT_BUFFER
		CP	10
		JR	NZ,.CHAR
		LD	A,13
		CALL	PUT_CHAR
		LD	A,10
		JR	.PUT
.CHAR
		CP	32
		JR	NC,.PUT
		LD	A,'.'
.PUT
		CALL	PUT_CHAR
		JR	PRINT_BUFFER

MATCH_DATA_CLOSED_TOKEN
		PUSH	HL
		PUSH	BC
		LD	A,B
		AND	A
		JR	NZ,.ENOUGH
		LD	A,C
		CP	DATA_CLOSED_LEN
		JR	C,.NO
.ENOUGH
		LD	DE,DATA_CLOSED_TOKEN
		LD	B,DATA_CLOSED_LEN
.NEXT
		LD	A,(DE)
		CP	(HL)
		JR	NZ,.NO
		INC	DE
		INC	HL
		DJNZ	.NEXT
		POP	BC
		POP	HL
		AND	A
		RET
.NO
		POP	BC
		POP	HL
		SCF
		RET

BUILD_PASV_ENDPOINT
		LD	HL,PASV_HOST_BUFF
		LD	A,(PASV_H1)
		CALL	APPEND_U8_TO_HL
		LD	A,'.'
		CALL	APPEND_CHAR_HL
		LD	A,(PASV_H2)
		CALL	APPEND_U8_TO_HL
		LD	A,'.'
		CALL	APPEND_CHAR_HL
		LD	A,(PASV_H3)
		CALL	APPEND_U8_TO_HL
		LD	A,'.'
		CALL	APPEND_CHAR_HL
		LD	A,(PASV_H4)
		CALL	APPEND_U8_TO_HL
		XOR	A
		LD	(HL),A

		LD	A,(PASV_P1)
		LD	L,A
		LD	H,0
		ADD	HL,HL
		ADD	HL,HL
		ADD	HL,HL
		ADD	HL,HL
		ADD	HL,HL
		ADD	HL,HL
		ADD	HL,HL
		ADD	HL,HL
		LD	A,(PASV_P2)
		LD	E,A
		LD	D,0
		ADD	HL,DE
		LD	DE,PASV_PORT_BUFF
		CALL	UTIL.UTOA
		RET

APPEND_U8_TO_HL
		PUSH	HL
		LD	L,A
		LD	H,0
		LD	DE,NUM_TMP_BUFF
		CALL	UTIL.UTOA
		POP	HL
		LD	DE,NUM_TMP_BUFF
		JP	APPEND_STR

APPEND_CHAR_HL
		LD	(HL),A
		INC	HL
		RET

CLEANUP_TCP
		LD	A,(DATA_OPEN)
		AND	A
		JR	Z,.CONTROL
		LD	A,DATA_LINK
		CALL	TCP.CLOSE_LINK
		XOR	A
		LD	(DATA_OPEN),A
.CONTROL
		LD	A,(CONTROL_OPEN)
		AND	A
		RET	Z
		LD	A,CONTROL_LINK
		CALL	TCP.CLOSE_LINK
		XOR	A
		LD	(CONTROL_OPEN),A
		RET

SEND_CMD
		LD	DE,WIFI.RS_BUFF
		LD	BC,DEFAULT_TIMEOUT
		CALL	WIFI.UART_TX_CMD
		AND	A
		RET	Z
		ADD	A,'0'
		LD	(MSG_ERROR_NO),A
		PRINTLN MSG_COMM_ERROR
		LD	B,3
		JP	WCOMMON.EXIT

SEND_CMD_IGNORE
		LD	DE,WIFI.RS_BUFF
		LD	BC,DEFAULT_TIMEOUT
		CALL	WIFI.UART_TX_CMD
		RET

SEND_CMD_RECOVER
		PUSH	HL
		LD	DE,WIFI.RS_BUFF
		LD	BC,DEFAULT_TIMEOUT
		CALL	WIFI.UART_TX_CMD
		AND	A
		JR	Z,.OK
		PRINTLN MSG_RESETTING_ESP
		CALL	WIFI.ESP_RESET
		CALL	WIFI.UART_SET_DEFAULT_DIVISOR
		CALL	WIFI.UART_INIT
		POP	HL
		JP	SEND_CMD
.OK
		POP	HL
		RET

APPEND_STR
		LD	A,(DE)
		AND	A
		RET	Z
		LD	(HL),A
		INC	HL
		INC	DE
		JR	APPEND_STR

APPEND_IX_STR
		LD	A,(IX+0)
		AND	A
		RET	Z
		LD	(HL),A
		INC	HL
		INC	IX
		JR	APPEND_IX_STR

PUT_CHAR
		PUSH	BC,HL
		LD	C,DSS_PUTCHAR
		RST	DSS
		POP	HL,BC
		RET

CLEAR_BSS
		LD	HL,FTP_BSS_BASE
		LD	DE,FTP_BSS_BASE+1
		LD	BC,FTP_BSS_END-FTP_BSS_BASE-1
		XOR	A
		LD	(HL),A
		LDIR
		RET

MSG_START
		DB "FTP - passive FTP LIST test for SprinterESP",0
MSG_USAGE
		DB "Usage: FTP.EXE host[:port] [user [password]]",0
MSG_WIFI_FOUND
		DB "Sprinter-WiFi found in ISA#"
MSG_SLOT_NO
		DB "n slot.",0
MSG_WIFI_NOT_FOUND
		DB "Sprinter-WiFi not found!",0
MSG_UART_READY
		DB "UART initialized.",0
MSG_RESETTING_ESP
		DB "ESP did not answer, resetting module.",0
MSG_CONNECTING
		DB "Connecting to ",0
MSG_COLON
		DB ":",0
MSG_LOGIN
		DB "Logging in.",0
MSG_BINARY
		DB "Setting binary transfer mode.",0
MSG_PASV
		DB "Requesting passive endpoint.",0
MSG_PASV_ENDPOINT
		DB "Passive endpoint: ",0
MSG_OPEN_DATA
		DB "Opening data link to ",0
MSG_LIST
		DB "Requesting directory listing.",0
MSG_LISTING
		DB "Directory listing:",0
MSG_DONE
		DB "FTP done.",0
MSG_COMM_ERROR
		DB "ESP communication error #"
MSG_ERROR_NO
		DB "n!",0
MSG_NET_ERROR
		DB "Network/ESP error #"
MSG_NET_ERROR_NO
		DB "n!",0
MSG_FTP_ERROR
		DB "FTP server returned error: ",0

CMD_AT
		DB "AT",13,10,0
CMD_ECHO_OFF
		DB "ATE0",13,10,0
CMD_CIPMUX_1
		DB "AT+CIPMUX=1",13,10,0
CMD_CRLF
		DB 13,10,0

DEFAULT_PORT
		DB "21",0
DEFAULT_USER
		DB "anonymous",0
DEFAULT_PASS
		DB "sprinter@example",0
FTP_USER_PREFIX
		DB "USER ",0
FTP_PASS_PREFIX
		DB "PASS ",0
FTP_TYPE_I
		DB "TYPE I",13,10,0
FTP_PASV
		DB "PASV",13,10,0
FTP_LIST
		DB "LIST",13,10,0
FTP_QUIT
		DB "QUIT",13,10,0
DATA_CLOSED_TOKEN
		DB "1,CLOSED"

ARG_LEN
		DB 0
CONTROL_OPEN
			DB 0
DATA_OPEN
			DB 0
DATA_CLOSE_SEEN
			DB 0
DATA_BYTES_SEEN
			DB 0
FINAL_REPLY_SEEN
		DB 0
CONTROL_TIMEOUT
		DW 0
CMD_LEN
			DW 0
LINE_LEN
		DB 0
REPLY_DONE
		DB 0
REPLY_FIRST
		DB 0
REPLY_CODE_1
		DB 0
REPLY_CODE_2
		DB 0
REPLY_CODE_3
		DB 0
PASV_H1
		DB 0
PASV_H2
		DB 0
PASV_H3
		DB 0
PASV_H4
		DB 0
PASV_P1
		DB 0
PASV_P2
		DB 0

		ENDMODULE

		INCLUDE "netcfg_lib.asm"
		INCLUDE "wcommon.asm"
		INCLUDE "dss_error.asm"
		INCLUDE "isa.asm"
		INCLUDE "esp_tcp.asm"
		INCLUDE "esp_tcp_multi.asm"
		INCLUDE "esplib.asm"

		MODULE MAIN

FTP_BSS_BASE	EQU NETCFG.NETCFG_BSS_END
HOST_BUFF	EQU FTP_BSS_BASE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
USER_BUFF	EQU PORT_BUFF + PORT_SIZE
PASS_BUFF	EQU USER_BUFF + USER_SIZE
CMD_BUFF	EQU PASS_BUFF + PASS_SIZE
RECV_BUFFER	EQU CMD_BUFF + CMD_SIZE
LINE_BUFF	EQU RECV_BUFFER + RECV_SIZE
PASV_HOST_BUFF	EQU LINE_BUFF + LINE_SIZE
PASV_PORT_BUFF	EQU PASV_HOST_BUFF + 16
NUM_TMP_BUFF	EQU PASV_PORT_BUFF + 8
FTP_BSS_END	EQU NUM_TMP_BUFF + 8

		ENDMODULE

		END MAIN.START
