; ======================================================
; NETCFG for Sprinter DSS Network Kit
; Display parsed NET.CFG values.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	ORG 0x8080

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 106, 0

	ORG 0x8100
@STACK_TOP

START
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	NETCFG.LOAD
	JR	NC,.LOADED

	CP	E_FILE_NOT_FOUND
	JR	NZ,.DSS_ERROR
	PRINTLN MSG_NOT_FOUND
	JR	.DISPLAY

.DSS_ERROR
	CALL	DSS_ERROR.EPRINT

.LOADED
	PRINTLN MSG_LOADED

.DISPLAY
	PRINT MSG_SSID
	PRINT NETCFG.CFG_SSID
	PRINT WCOMMON.LINE_END

	PRINT MSG_PASS
	LD	A,(NETCFG.CFG_PASS)
	AND	A
	JR	Z,.PASS_EMPTY
	PRINT MSG_PASS_SET
	JR	.PASS_DONE
.PASS_EMPTY
	PRINT MSG_PASS_EMPTY
.PASS_DONE
	PRINT WCOMMON.LINE_END

	PRINT MSG_DHCP
	PRINT NETCFG.CFG_DHCP
	PRINT WCOMMON.LINE_END

	PRINT MSG_IP
	PRINT NETCFG.CFG_IP
	PRINT WCOMMON.LINE_END

	PRINT MSG_GATEWAY
	PRINT NETCFG.CFG_GATEWAY
	PRINT WCOMMON.LINE_END

	PRINT MSG_NETMASK
	PRINT NETCFG.CFG_NETMASK
	PRINT WCOMMON.LINE_END

	PRINT MSG_DNS1
	PRINT NETCFG.CFG_DNS1
	PRINT WCOMMON.LINE_END

	PRINT MSG_DNS2
	PRINT NETCFG.CFG_DNS2
	PRINT WCOMMON.LINE_END

	PRINT MSG_TZ
	PRINT NETCFG.CFG_TZ
	PRINT WCOMMON.LINE_END

	PRINT MSG_NTP
	PRINT NETCFG.CFG_NTP
	PRINT WCOMMON.LINE_END

	PRINT MSG_AUTOJOIN
	PRINT NETCFG.CFG_AUTOJOIN
	PRINT WCOMMON.LINE_END

	LD	B,0
	JP	WCOMMON.EXIT

MSG_START
	DB "NETCFG - Sprinter DSS Network Kit configuration",0
MSG_LOADED
	DB "Loaded NET.CFG.",0
MSG_NOT_FOUND
	DB "NET.CFG not found, showing defaults.",0

MSG_SSID	DB "SSID: ",0
MSG_PASS	DB "PASS: ",0
MSG_PASS_SET	DB "<set>",0
MSG_PASS_EMPTY	DB "<empty>",0
MSG_DHCP	DB "DHCP: ",0
MSG_IP		DB "IP: ",0
MSG_GATEWAY	DB "GATEWAY: ",0
MSG_NETMASK	DB "NETMASK: ",0
MSG_DNS1	DB "DNS1: ",0
MSG_DNS2	DB "DNS2: ",0
MSG_TZ		DB "TZ: ",0
MSG_NTP		DB "NTP: ",0
MSG_AUTOJOIN	DB "AUTOJOIN: ",0

	ENDMODULE

	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "netcfg_lib.asm"
	INCLUDE "esplib.asm"

	END MAIN.START
