; ======================================================
; NETCFG for Sprinter DSS Network Kit
; Display parsed NET.CFG values.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	ORG 0x8080

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 106, 0

	ORG 0x8100
@STACK_TOP

START
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	NETCFG.LOAD
	JR	NC,.LOADED

	CP	E_FILE_NOT_FOUND
	JR	NZ,.DSS_ERROR
	PRINTLN MSG_NOT_FOUND
	JR	.DISPLAY

.DSS_ERROR
	CALL	DSS_ERROR.EPRINT

.LOADED
	PRINTLN MSG_LOADED

.DISPLAY
	CALL	CHECK_WRITE_MODE
	JP	C,WRITE_CONFIG

DISPLAY_CONFIG
	PRINT MSG_SSID
	PRINT NETCFG.CFG_SSID
	PRINT WCOMMON.LINE_END

	PRINT MSG_PASS
	LD	A,(NETCFG.CFG_PASS)
	AND	A
	JR	Z,.PASS_EMPTY
	PRINT MSG_PASS_SET
	JR	.PASS_DONE
.PASS_EMPTY
	PRINT MSG_PASS_EMPTY
.PASS_DONE
	PRINT WCOMMON.LINE_END

	PRINT MSG_DHCP
	PRINT NETCFG.CFG_DHCP
	PRINT WCOMMON.LINE_END

	PRINT MSG_IP
	PRINT NETCFG.CFG_IP
	PRINT WCOMMON.LINE_END

	PRINT MSG_GATEWAY
	PRINT NETCFG.CFG_GATEWAY
	PRINT WCOMMON.LINE_END

	PRINT MSG_NETMASK
	PRINT NETCFG.CFG_NETMASK
	PRINT WCOMMON.LINE_END

	PRINT MSG_DNS1
	PRINT NETCFG.CFG_DNS1
	PRINT WCOMMON.LINE_END

	PRINT MSG_DNS2
	PRINT NETCFG.CFG_DNS2
	PRINT WCOMMON.LINE_END

	PRINT MSG_TZ
	PRINT NETCFG.CFG_TZ
	PRINT WCOMMON.LINE_END

	PRINT MSG_NTP
	PRINT NETCFG.CFG_NTP
	PRINT WCOMMON.LINE_END

	PRINT MSG_AUTOJOIN
	PRINT NETCFG.CFG_AUTOJOIN
	PRINT WCOMMON.LINE_END

	LD	B,0
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Check command line for /W or -W.
; Out: CF=1 - write mode requested.
; ------------------------------------------------------
CHECK_WRITE_MODE
	LD	HL,0x8080
	LD	A,(HL)
	AND	A
	RET	Z
	LD	B,A
	INC	HL
.NEXT
	LD	A,(HL)
	CP	'/'
	JR	Z,.MAYBE_W
	CP	'-'
	JR	Z,.MAYBE_W
.CONT
	INC	HL
	DJNZ	.NEXT
	AND	A
	RET
.MAYBE_W
	INC	HL
	DEC	B
	JR	Z,.NO
	LD	A,(HL)
	CP	'W'
	JR	Z,.YES
	CP	'w'
	JR	Z,.YES
	JR	.CONT
.YES
	SCF
	RET
.NO
	AND	A
	RET

; ------------------------------------------------------
; Interactive NET.CFG writer.
; ------------------------------------------------------
WRITE_CONFIG
	PRINTLN MSG_WRITE_MODE
	PRINTLN MSG_WRITE_WARN

	LD	HL,MSG_PROMPT_SSID
	LD	DE,NETCFG.CFG_SSID
	LD	B,NETCFG.CFG_SSID_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_PASS
	LD	DE,NETCFG.CFG_PASS
	LD	B,NETCFG.CFG_PASS_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_DHCP
	LD	DE,NETCFG.CFG_DHCP
	LD	B,NETCFG.CFG_FLAG_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_IP
	LD	DE,NETCFG.CFG_IP
	LD	B,NETCFG.CFG_ADDR_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_GATEWAY
	LD	DE,NETCFG.CFG_GATEWAY
	LD	B,NETCFG.CFG_ADDR_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_NETMASK
	LD	DE,NETCFG.CFG_NETMASK
	LD	B,NETCFG.CFG_ADDR_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_DNS1
	LD	DE,NETCFG.CFG_DNS1
	LD	B,NETCFG.CFG_ADDR_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_DNS2
	LD	DE,NETCFG.CFG_DNS2
	LD	B,NETCFG.CFG_ADDR_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_TZ
	LD	DE,NETCFG.CFG_TZ
	LD	B,NETCFG.CFG_TZ_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_NTP
	LD	DE,NETCFG.CFG_NTP
	LD	B,NETCFG.CFG_NTP_SIZE
	CALL	READ_CONFIG_VALUE

	LD	HL,MSG_PROMPT_AUTOJOIN
	LD	DE,NETCFG.CFG_AUTOJOIN
	LD	B,NETCFG.CFG_FLAG_SIZE
	CALL	READ_CONFIG_VALUE

	CALL	NETCFG.SAVE
	JP	C,DSS_ERROR.EPRINT

	PRINTLN MSG_SAVED
	JP	DISPLAY_CONFIG

; ------------------------------------------------------
; Prompt and read a line. Empty input keeps existing value.
; In: HL - prompt, DE - destination, B - destination size.
; ------------------------------------------------------
READ_CONFIG_VALUE
	PUSH	DE,BC
	PRINT_HL
	PRINT MSG_CURRENT_PREFIX
	POP	BC,DE
	PUSH	DE,BC
	EX	DE,HL
	PRINT_HL
	PRINT MSG_CURRENT_SUFFIX
	POP	BC,DE

	PUSH	DE,BC
	LD	HL,INPUT_BUFF
	LD	B,INPUT_BUFF_SIZE
	CALL	READ_LINE
	LD	A,(INPUT_BUFF)
	AND	A
	JR	Z,.KEEP
	POP	BC,DE
	LD	HL,INPUT_BUFF
	CALL	COPY_INPUT_TO_DEST
	RET
.KEEP
	POP	BC,DE
	RET

; ------------------------------------------------------
; Read line to HL, max B bytes including zero.
; ------------------------------------------------------
READ_LINE
	LD	D,H
	LD	E,L
	DEC	B
.NEXT
	LD	C,DSS_ECHOKEY
	RST	DSS
	CP	13
	JR	Z,.END
	CP	10
	JR	Z,.END
	LD	(DE),A
	INC	DE
	DJNZ	.NEXT
.FLUSH
	LD	C,DSS_ECHOKEY
	RST	DSS
	CP	13
	JR	NZ,.FLUSH
.END
	XOR	A
	LD	(DE),A
	PRINT WCOMMON.LINE_END
	RET

; ------------------------------------------------------
; Copy input in HL to destination DE. B is destination size.
; ------------------------------------------------------
COPY_INPUT_TO_DEST
	DEC	B
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.END
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	.NEXT
.END
	XOR	A
	LD	(DE),A
	RET

MSG_START
	DB "NETCFG - Sprinter DSS Network Kit configuration",0
MSG_LOADED
	DB "Loaded NET.CFG.",0
MSG_NOT_FOUND
	DB "NET.CFG not found, showing defaults.",0

MSG_SSID	DB "SSID: ",0
MSG_PASS	DB "PASS: ",0
MSG_PASS_SET	DB "<set>",0
MSG_PASS_EMPTY	DB "<empty>",0
MSG_DHCP	DB "DHCP: ",0
MSG_IP		DB "IP: ",0
MSG_GATEWAY	DB "GATEWAY: ",0
MSG_NETMASK	DB "NETMASK: ",0
MSG_DNS1	DB "DNS1: ",0
MSG_DNS2	DB "DNS2: ",0
MSG_TZ		DB "TZ: ",0
MSG_NTP		DB "NTP: ",0
MSG_AUTOJOIN	DB "AUTOJOIN: ",0

MSG_WRITE_MODE
	DB "Interactive write mode.",0
MSG_WRITE_WARN
	DB "Warning: Wi-Fi password will be saved as clear text.",0
MSG_SAVED
	DB "NET.CFG saved.",0
MSG_CURRENT_PREFIX
	DB " [",0
MSG_CURRENT_SUFFIX
	DB "]: ",0

MSG_PROMPT_SSID	DB "SSID",0
MSG_PROMPT_PASS	DB "PASS",0
MSG_PROMPT_DHCP	DB "DHCP",0
MSG_PROMPT_IP	DB "IP",0
MSG_PROMPT_GATEWAY	DB "GATEWAY",0
MSG_PROMPT_NETMASK	DB "NETMASK",0
MSG_PROMPT_DNS1	DB "DNS1",0
MSG_PROMPT_DNS2	DB "DNS2",0
MSG_PROMPT_TZ	DB "TZ",0
MSG_PROMPT_NTP	DB "NTP",0
MSG_PROMPT_AUTOJOIN	DB "AUTOJOIN",0

INPUT_BUFF_SIZE	EQU 80
INPUT_BUFF	DS INPUT_BUFF_SIZE,0

	ENDMODULE

	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "netcfg_lib.asm"
	INCLUDE "esplib.asm"

	END MAIN.START
