; ======================================================
; NTP for Sprinter DSS Network Kit
; Set DSS time using ESP-AT SNTP support.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
SNTP_TIMEOUT		EQU 8000
CMD_SIZE		EQU 160
TIME_RETRIES		EQU 5

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	ORG 0x8080

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 106, 0

	ORG 0x8100
@STACK_TOP

START
	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI

	CALL	NETCFG.LOAD
	CALL	NETCFG.APPLY_UART_BAUD
	CALL	WIFI.UART_INIT
	PRINTLN MSG_UART_READY

	LD	HL,CMD_AT
	CALL	SEND_CMD_RECOVER

	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD

	PRINT MSG_SERVER
	PRINT NETCFG.CFG_NTP
	PRINT MSG_TZ
	PRINT NETCFG.CFG_TZ
	PRINT WCOMMON.LINE_END

	CALL	BUILD_SNTP_CFG_CMD
	LD	HL,CMD_BUFF
	LD	DE,WIFI.RS_BUFF
	LD	BC,SNTP_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	Z,.CFG_OK
	CP	RES_ERROR
	JP	Z,.UNSUPPORTED
	CP	RES_FAIL
	JP	Z,.UNSUPPORTED
	JP	COMM_ERROR_A

.CFG_OK
	PRINTLN MSG_SYNC
	LD	A,TIME_RETRIES
	LD	(RETRY_COUNT),A
.RETRY
	LD	HL,1000
	CALL	UTIL.DELAY
	LD	HL,CMD_SNTP_TIME
	LD	DE,WIFI.RS_BUFF
	LD	BC,SNTP_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	NZ,.TIME_ERROR
	CALL	PARSE_SNTP_RESPONSE
	JR	NC,.TIME_OK
	LD	HL,RETRY_COUNT
	DEC	(HL)
	JR	NZ,.RETRY
	PRINTLN MSG_PARSE_ERROR
	PRINTLN MSG_RAW_RESPONSE
	LD	HL,WIFI.RS_BUFF
	CALL	PRINT_ESP_RESPONSE
	LD	B,3
	JP	WCOMMON.EXIT

.TIME_ERROR
	CP	RES_ERROR
	JR	Z,.UNSUPPORTED
	CP	RES_FAIL
	JR	Z,.UNSUPPORTED
	JP	COMM_ERROR_A

.TIME_OK
	CALL	PRINT_PARSED_TIME
	CALL	SET_DSS_TIME
	JR	C,.SET_ERROR
	PRINTLN MSG_DONE
	LD	B,0
	JP	WCOMMON.EXIT

.SET_ERROR
	PRINTLN MSG_SET_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

.UNSUPPORTED
	PRINTLN MSG_UNSUPPORTED
	LD	B,3
	JP	WCOMMON.EXIT

NO_WIFI
	PRINTLN MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

COMM_ERROR_A
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_COMM_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Send command in HL with default timeout.
; ------------------------------------------------------
SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	RET	Z
	JP	COMM_ERROR_A

; ------------------------------------------------------
; Send command in HL. Reset ESP once if it does not answer.
; ------------------------------------------------------
SEND_CMD_RECOVER
	PUSH	HL
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	Z,.OK

	PRINTLN MSG_RESETTING_ESP
	CALL	WIFI.ESP_RESET
	CALL	WIFI.UART_SET_DEFAULT_DIVISOR
	CALL	WIFI.UART_INIT
	POP	HL
	JP	SEND_CMD

.OK
	POP	HL
	RET

; ------------------------------------------------------
; Build AT+CIPSNTPCFG=1,<tz>,"server".
; ------------------------------------------------------
BUILD_SNTP_CFG_CMD
	LD	HL,CMD_BUFF
	LD	DE,CMD_SNTP_CFG_PREFIX
	CALL	APPEND_STR
	LD	IX,NETCFG.CFG_TZ
	CALL	APPEND_IX_STR
	LD	DE,CMD_SNTP_CFG_MIDDLE
	CALL	APPEND_STR
	LD	IX,NETCFG.CFG_NTP
	CALL	APPEND_IX_STR
	LD	DE,CMD_QUOTE_CRLF
	JP	APPEND_STR

; ------------------------------------------------------
; Parse +CIPSNTPTIME:Wed Apr 29 09:49:36 2026.
; Out: CF=0 parsed, CF=1 not found or invalid.
; ------------------------------------------------------
PARSE_SNTP_RESPONSE
	LD	HL,WIFI.RS_BUFF
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	LD	DE,RESP_TIME_PREFIX
	CALL	UTIL.STARTSWITH
	JR	Z,.FOUND
	CALL	SKIP_LINE
	JR	.NEXT
.FOUND
	LD	BC,13
	ADD	HL,BC
	CALL	SKIP_SPACES
	CALL	SKIP_TOKEN
	JR	C,.ERR
	CALL	SKIP_SPACES
	CALL	PARSE_MONTH
	JR	C,.ERR
	LD	(PARSED_MONTH),A
	CALL	SKIP_SPACES
	CALL	PARSE_DEC_A
	JR	C,.ERR
	LD	(PARSED_DAY),A
	CALL	SKIP_SPACES
	CALL	PARSE_DEC_A
	JR	C,.ERR
	LD	(PARSED_HOUR),A
	LD	A,(HL)
	CP	':'
	JR	NZ,.ERR
	INC	HL
	CALL	PARSE_DEC_A
	JR	C,.ERR
	LD	(PARSED_MINUTE),A
	LD	A,(HL)
	CP	':'
	JR	NZ,.ERR
	INC	HL
	CALL	PARSE_DEC_A
	JR	C,.ERR
	LD	(PARSED_SECOND),A
	CALL	SKIP_SPACES
	CALL	PARSE_YEAR
	JR	C,.ERR
	LD	DE,2020
	AND	A
	SBC	HL,DE
	JR	C,.ERR
	ADD	HL,DE
	LD	(PARSED_YEAR),HL
	AND	A
	RET
.ERR
	SCF
	RET

SKIP_LINE
	LD	A,(HL)
	AND	A
	RET	Z
	INC	HL
	CP	10
	RET	Z
	JR	SKIP_LINE

SKIP_SPACES
	LD	A,(HL)
	CP	' '
	JR	Z,.SKIP
	CP	9
	RET	NZ
.SKIP
	INC	HL
	JR	SKIP_SPACES

SKIP_TOKEN
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	CP	' '
	RET	Z
	CP	9
	RET	Z
	INC	HL
	JR	SKIP_TOKEN
.ERR
	SCF
	RET

PARSE_MONTH
	LD	DE,MON_JAN
	CALL	UTIL.STARTSWITH
	LD	A,1
	JR	Z,.OK
	LD	DE,MON_FEB
	CALL	UTIL.STARTSWITH
	LD	A,2
	JR	Z,.OK
	LD	DE,MON_MAR
	CALL	UTIL.STARTSWITH
	LD	A,3
	JR	Z,.OK
	LD	DE,MON_APR
	CALL	UTIL.STARTSWITH
	LD	A,4
	JR	Z,.OK
	LD	DE,MON_MAY
	CALL	UTIL.STARTSWITH
	LD	A,5
	JR	Z,.OK
	LD	DE,MON_JUN
	CALL	UTIL.STARTSWITH
	LD	A,6
	JR	Z,.OK
	LD	DE,MON_JUL
	CALL	UTIL.STARTSWITH
	LD	A,7
	JR	Z,.OK
	LD	DE,MON_AUG
	CALL	UTIL.STARTSWITH
	LD	A,8
	JR	Z,.OK
	LD	DE,MON_SEP
	CALL	UTIL.STARTSWITH
	LD	A,9
	JR	Z,.OK
	LD	DE,MON_OCT
	CALL	UTIL.STARTSWITH
	LD	A,10
	JR	Z,.OK
	LD	DE,MON_NOV
	CALL	UTIL.STARTSWITH
	LD	A,11
	JR	Z,.OK
	LD	DE,MON_DEC
	CALL	UTIL.STARTSWITH
	LD	A,12
	JR	Z,.OK
	SCF
	RET
.OK
	INC	HL
	INC	HL
	INC	HL
	AND	A
	RET

PARSE_DEC_A
	LD	C,0
	LD	E,0
.NEXT
	LD	A,(HL)
	CP	'0'
	JR	C,.END
	CP	'9'+1
	JR	NC,.END
	SUB	'0'
	LD	B,A
	LD	A,C
	ADD	A,A
	LD	D,A
	ADD	A,A
	ADD	A,A
	ADD	A,D
	ADD	A,B
	LD	C,A
	INC	E
	INC	HL
	JR	.NEXT
.END
	LD	A,E
	AND	A
	JR	Z,.ERR
	LD	A,C
	AND	A
	RET
.ERR
	SCF
	RET

PARSE_YEAR
	LD	A,(HL)
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	EX	DE,HL
	CALL	UTIL.ATOU
	EX	DE,HL
	EX	DE,HL
	AND	A
	RET
.ERR
	SCF
	RET

; ------------------------------------------------------
; Set DSS system time from parsed fields.
; ------------------------------------------------------
SET_DSS_TIME
	LD	A,(PARSED_DAY)
	LD	D,A
	LD	A,(PARSED_MONTH)
	LD	E,A
	LD	HL,(PARSED_YEAR)
	PUSH	HL
	POP	IX
	LD	A,(PARSED_HOUR)
	LD	H,A
	LD	A,(PARSED_MINUTE)
	LD	L,A
	LD	A,(PARSED_SECOND)
	LD	B,A
	LD	C,DSS_SETTIME
	RST	DSS
	RET

PRINT_PARSED_TIME
	PRINT MSG_TIME
	LD	A,(PARSED_YEAR)
	LD	L,A
	LD	A,(PARSED_YEAR+1)
	LD	H,A
	CALL	PRINT_HL_DEC
	LD	A,'-'
	CALL	PUT_CHAR
	LD	A,(PARSED_MONTH)
	CALL	PRINT_A_2
	LD	A,'-'
	CALL	PUT_CHAR
	LD	A,(PARSED_DAY)
	CALL	PRINT_A_2
	LD	A,' '
	CALL	PUT_CHAR
	LD	A,(PARSED_HOUR)
	CALL	PRINT_A_2
	LD	A,':'
	CALL	PUT_CHAR
	LD	A,(PARSED_MINUTE)
	CALL	PRINT_A_2
	LD	A,':'
	CALL	PUT_CHAR
	LD	A,(PARSED_SECOND)
	CALL	PRINT_A_2
	PRINT	WCOMMON.LINE_END
	RET

PRINT_A_2
	LD	L,A
	LD	H,0
	LD	DE,NUM_BUFF
	CALL	UTIL.UTOA
	LD	A,(NUM_BUFF+1)
	AND	A
	JR	NZ,.PRINT
	LD	A,'0'
	CALL	PUT_CHAR
.PRINT
	PRINT	NUM_BUFF
	RET

PRINT_HL_DEC
	LD	DE,NUM_BUFF
	CALL	UTIL.UTOA
	PRINT	NUM_BUFF
	RET

; ------------------------------------------------------
; Print ESP response buffer with LF -> CRLF conversion.
; ------------------------------------------------------
PRINT_ESP_RESPONSE
	LD	A,(HL)
	AND	A
	JR	Z,.DONE
	CP	10
	JR	NZ,.PUT_CHAR
	LD	A,13
	CALL	PUT_CHAR
	LD	A,10
.PUT_CHAR
	CALL	PUT_CHAR
	INC	HL
	JR	PRINT_ESP_RESPONSE
.DONE
	LD	A,13
	CALL	PUT_CHAR
	LD	A,10
	JP	PUT_CHAR

PUT_CHAR
	PUSH	HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL
	RET

APPEND_STR
	LD	A,(DE)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	DE
	JR	APPEND_STR

APPEND_IX_STR
	LD	A,(IX+0)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	IX
	JR	APPEND_IX_STR

MSG_START
	DB "NTP - set DSS time from ESP SNTP",0
MSG_UART_READY
	DB "UART initialized.",0
MSG_RESETTING_ESP
	DB "ESP did not answer, resetting module.",0
MSG_WIFI_NOT_FOUND
	DB "Sprinter-WiFi not found!",0
MSG_SERVER
	DB "SNTP server: ",0
MSG_TZ
	DB " TZ: ",0
MSG_SYNC
	DB "Waiting for SNTP time.",0
MSG_TIME
	DB "Time: ",0
MSG_DONE
	DB "NTP done.",0
MSG_UNSUPPORTED
	DB "ESP SNTP command is unsupported or failed.",0
MSG_PARSE_ERROR
	DB "No valid SNTP time received.",0
MSG_RAW_RESPONSE
	DB "Raw ESP response:",0
MSG_SET_ERROR
	DB "DSS SETTIME failed.",0
MSG_COMM_ERROR
	DB "ESP communication error #"
MSG_ERROR_NO
	DB "n!",0

CMD_AT
	DB "AT",13,10,0
CMD_ECHO_OFF
	DB "ATE0",13,10,0
CMD_SNTP_CFG_PREFIX
	DB "AT+CIPSNTPCFG=1,",0
CMD_SNTP_CFG_MIDDLE
	DB ",",34,0
CMD_QUOTE_CRLF
	DB 34,13,10,0
CMD_SNTP_TIME
	DB "AT+CIPSNTPTIME?",13,10,0

RESP_TIME_PREFIX
	DB "+CIPSNTPTIME:",0

MON_JAN	DB "Jan",0
MON_FEB	DB "Feb",0
MON_MAR	DB "Mar",0
MON_APR	DB "Apr",0
MON_MAY	DB "May",0
MON_JUN	DB "Jun",0
MON_JUL	DB "Jul",0
MON_AUG	DB "Aug",0
MON_SEP	DB "Sep",0
MON_OCT	DB "Oct",0
MON_NOV	DB "Nov",0
MON_DEC	DB "Dec",0

RETRY_COUNT	DB 0
PARSED_DAY	DB 0
PARSED_MONTH	DB 0
PARSED_HOUR	DB 0
PARSED_MINUTE	DB 0
PARSED_SECOND	DB 0
PARSED_YEAR	DW 0
CMD_BUFF	DS CMD_SIZE,0
NUM_BUFF	DS 8,0

	ENDMODULE

	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "netcfg_lib.asm"
	INCLUDE "esplib.asm"

	END MAIN.START
