; ======================================================
; TCPTEST for Sprinter DSS Network Kit
; Minimal TCP smoke test over ESP-AT.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
RECV_TIMEOUT		EQU 5000
RECV_BUFFER_SIZE	EQU 512
RECV_BLOCK_LIMIT	EQU 4
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
PATH_SIZE		EQU 128
REQ_SIZE		EQU 320

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	ORG 0x8080

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 106, 0

	ORG 0x8100
@STACK_TOP

START
	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	INIT_DEFAULT_ARGS
	CALL	PARSE_CMD_LINE
	JP	C,USAGE
	CALL	SET_PORT_FLAG

	PRINT	MSG_TARGET
	PRINT	HOST_BUFF
	PRINT	MSG_COLON
	PRINT	PORT_BUFF
	PRINT	PATH_BUFF
	PRINT	WCOMMON.LINE_END

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI

	LD	A,(ISA.ISA_SLOT)
	ADD	A,'1'
	LD	(MSG_SLOT_NO),A
	PRINTLN MSG_WIFI_FOUND

	CALL	NETCFG.LOAD
	CALL	NETCFG.APPLY_UART_BAUD
	CALL	WIFI.UART_INIT
	PRINTLN MSG_UART_READY

	LD	HL,CMD_AT
	CALL	SEND_CMD_RECOVER

	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD

	LD	HL,CMD_CIPMUX_0
	CALL	SEND_CMD

	PRINT MSG_CONNECTING
	PRINT HOST_BUFF
	PRINT WCOMMON.LINE_END
	LD	HL,HOST_BUFF
	LD	DE,PORT_BUFF
	CALL	TCP.OPEN
	CALL	CHECK_TCP_ERROR

	PRINTLN MSG_SENDING
	CALL	BUILD_HTTP_REQUEST
	LD	HL,REQ_BUFF
	CALL	UTIL.STRLEN
	CALL	TCP.SEND_BUFFER
	CALL	CHECK_TCP_ERROR

	PRINTLN MSG_RESPONSE
	LD	A,RECV_BLOCK_LIMIT
	LD	(RECV_BLOCKS),A
.RECV_LOOP
	LD	HL,RECV_BUFFER
	LD	BC,RECV_BUFFER_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	TCP.RECEIVE
	JR	C,.CLOSE
	LD	A,B
	OR	C
	JR	Z,.CLOSE
	LD	HL,RECV_BUFFER
	CALL	PRINT_BUFFER
	LD	HL,RECV_BLOCKS
	DEC	(HL)
	JR	NZ,.RECV_LOOP

.CLOSE
	PRINT WCOMMON.LINE_END
	CALL	TCP.CLOSE
	PRINTLN MSG_DONE
	LD	B,0
	JP	WCOMMON.EXIT

NO_WIFI
	PRINTLN MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

USAGE
	PRINTLN MSG_USAGE
	LD	B,1
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Optional command line: TCPTEST.EXE [host [port [path]]]
; ------------------------------------------------------
INIT_DEFAULT_ARGS
	LD	HL,DEFAULT_HOST
	LD	DE,HOST_BUFF
	CALL	COPY_ASCIIZ_DE
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	CALL	COPY_ASCIIZ_DE
	LD	HL,DEFAULT_PATH
	LD	DE,PATH_BUFF
	JP	COPY_ASCIIZ_DE

PARSE_CMD_LINE
	LD	HL,0x8080
	LD	A,(HL)
	AND	A
	RET	Z
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JR	NC,.HOST
	AND	A
	RET
.HOST
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	CALL	SKIP_SPACES
	JR	NC,.PORT
	AND	A
	RET
.PORT
	LD	DE,PORT_BUFF
	LD	C,PORT_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	CALL	VALIDATE_PORT
	JR	C,.ERR
	CALL	SKIP_SPACES
	JR	NC,.PATH
	AND	A
	RET
.PATH
	LD	DE,PATH_BUFF
	CALL	COPY_PATH_ARG
	JR	C,.ERR
	CALL	SKIP_SPACES
	JR	NC,.ERR
	AND	A
	RET
.ERR
	SCF
	RET

SKIP_SPACES
	LD	A,B
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	XOR	A
	LD	(ARG_LEN),A
.NEXT
	LD	A,B
	AND	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	DEC	C
	LD	A,(ARG_LEN)
	INC	A
	LD	(ARG_LEN),A
	JR	.NEXT
.END
	XOR	A
	LD	(DE),A
	LD	A,(ARG_LEN)
	AND	A
	RET	NZ
.ERR
	SCF
	RET

COPY_PATH_ARG
	LD	A,(HL)
	CP	'/'
	JR	Z,.COPY
	LD	A,'/'
	LD	(DE),A
	INC	DE
	LD	C,PATH_SIZE-2
	JP	COPY_ARG
.COPY
	LD	C,PATH_SIZE-1
	JP	COPY_ARG

VALIDATE_PORT
	LD	HL,PORT_BUFF
.NEXT
	LD	A,(HL)
	AND	A
	RET	Z
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	INC	HL
	JR	.NEXT
.ERR
	SCF
	RET

COPY_ASCIIZ_DE
	LD	A,(HL)
	LD	(DE),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ_DE

BUILD_HTTP_REQUEST
	LD	HL,REQ_BUFF
	LD	DE,REQ_GET
	CALL	APPEND_STR
	LD	IX,PATH_BUFF
	CALL	APPEND_IX_STR
	LD	DE,REQ_HTTP
	CALL	APPEND_STR
	LD	IX,HOST_BUFF
	CALL	APPEND_IX_STR
	LD	A,(PORT_IS_DEFAULT)
	AND	A
	JR	NZ,.NO_HOST_PORT
	LD	DE,MSG_COLON
	CALL	APPEND_STR
	LD	IX,PORT_BUFF
	CALL	APPEND_IX_STR
.NO_HOST_PORT
	LD	DE,REQ_END
	JP	APPEND_STR

SET_PORT_FLAG
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	CALL	UTIL.STRCMP
	JR	C,.CUSTOM
	LD	A,1
	LD	(PORT_IS_DEFAULT),A
	RET
.CUSTOM
	XOR	A
	LD	(PORT_IS_DEFAULT),A
	RET

; ------------------------------------------------------
; Send command in HL with default timeout.
; ------------------------------------------------------
SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	RET	Z
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_COMM_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Send command in HL. Reset ESP once if it does not answer.
; ------------------------------------------------------
SEND_CMD_RECOVER
	PUSH	HL
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	Z,.OK

	PRINTLN MSG_RESETTING_ESP
	CALL	WIFI.ESP_RESET
	CALL	WIFI.UART_SET_DEFAULT_DIVISOR
	CALL	WIFI.UART_INIT
	POP	HL
	JP	SEND_CMD

.OK
	POP	HL
	RET

; ------------------------------------------------------
; Exit on TCP helper failure.
; ------------------------------------------------------
CHECK_TCP_ERROR
	RET	NC
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_COMM_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Print raw TCP data as console text.
; In: HL - data, BC - length.
; ------------------------------------------------------
PRINT_BUFFER
	LD	A,B
	OR	C
	RET	Z
	LD	A,(HL)
	INC	HL
	DEC	BC
	CP	13
	JR	Z,PRINT_BUFFER
	CP	10
	JR	NZ,.CHAR
	LD	A,13
	CALL	PUT_CHAR
	LD	A,10
	JR	.PUT
.CHAR
	CP	32
	JR	NC,.PUT
	LD	A,'.'
.PUT
	CALL	PUT_CHAR
	JR	PRINT_BUFFER

PUT_CHAR
	PUSH	BC,HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL,BC
	RET

APPEND_STR
	LD	A,(DE)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	DE
	JR	APPEND_STR

APPEND_IX_STR
	LD	A,(IX+0)
	AND	A
	RET	Z
	LD	(HL),A
	INC	HL
	INC	IX
	JR	APPEND_IX_STR

MSG_START
	DB "TCPTEST - ESP-AT TCP smoke test",0
MSG_USAGE
	DB "Usage: TCPTEST.EXE [host [port [path]]]",0
MSG_TARGET
	DB "Run NETUP first. Test target is ",0
MSG_WIFI_FOUND
	DB "Sprinter-WiFi found in ISA#"
MSG_SLOT_NO
	DB "n slot.",0
MSG_WIFI_NOT_FOUND
	DB "Sprinter-WiFi not found!",0
MSG_UART_READY
	DB "UART initialized.",0
MSG_RESETTING_ESP
	DB "ESP did not answer, resetting module.",0
MSG_CONNECTING
	DB "Connecting to ",0
MSG_COLON
	DB ":",0
MSG_SENDING
	DB "Sending HTTP request.",0
MSG_RESPONSE
	DB "Response:",0
MSG_DONE
	DB "TCPTEST done.",0
MSG_COMM_ERROR
	DB "ESP communication error #"
MSG_ERROR_NO
	DB "n!",0

CMD_AT
	DB "AT",13,10,0
CMD_ECHO_OFF
	DB "ATE0",13,10,0
CMD_CIPMUX_0
	DB "AT+CIPMUX=0",13,10,0

DEFAULT_HOST
	DB "example.com",0
DEFAULT_PORT
	DB "80",0
DEFAULT_PATH
	DB "/",0

REQ_GET
	DB "GET ",0
REQ_HTTP
	DB " HTTP/1.0",13,10,"Host: ",0
REQ_END
	DB 13,10
	DB "Connection: close",13,10
	DB 13,10,0

ARG_LEN
	DB 0
PORT_IS_DEFAULT
	DB 0
RECV_BLOCKS
	DB 0
HOST_BUFF
	DS HOST_SIZE,0
PORT_BUFF
	DS PORT_SIZE,0
PATH_BUFF
	DS PATH_SIZE,0
REQ_BUFF
	DS REQ_SIZE,0
RECV_BUFFER
	DS RECV_BUFFER_SIZE,0

	ENDMODULE

	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "netcfg_lib.asm"
	INCLUDE "esp_tcp.asm"
	INCLUDE "esplib.asm"

	END MAIN.START
