; ======================================================
; TFTP client for Sprinter DSS Network Kit
; Minimal RFC 1350 RRQ/WRQ client over ESP-AT UDP.
; ======================================================

EXE_VERSION		EQU 1
DEFAULT_TIMEOUT		EQU 2000
RECV_TIMEOUT		EQU 5000
; UDP datagrams can be dropped silently by ESP/Wi-Fi/network. Bumping the
; retry budget tolerates a few lost packets before failing the transfer.
RETRY_LIMIT		EQU 6
URL_SIZE		EQU 160
HOST_SIZE		EQU 96
PORT_SIZE		EQU 8
REMOTE_FILE_SIZE	EQU 128
LOCAL_FILE_SIZE	EQU 80
TFTP_PACKET_SIZE	EQU 516
TFTP_DATA_SIZE		EQU 512
DSS_CREATE_OVERWRITE	EQU 0x0A
NO_HANDLE		EQU 0xFF

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

	MODULE MAIN

	ORG 0x8080

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 106, 0

	ORG 0x8100
@STACK_TOP

START
	CALL	CLEAR_BSS
	LD	A,NO_HANDLE
	LD	(OUT_FH),A
	LD	(IN_FH),A
	XOR	A
	LD	(UDP_IS_OPEN),A
	LD	(TRANSFER_DONE),A
	LD	(TRANSFER_MODE),A
	LD	(FILE_ERROR_FLAG),A
	LD	(FILE_ERROR_CODE),A

	CALL	ISA.ISA_RESET
	CALL	WCOMMON.INIT_VMODE
	PRINTLN MSG_START

	CALL	PARSE_CMD_LINE
	JP	C,USAGE
	CALL	PARSE_URL
	JP	C,USAGE
	CALL	PRINT_SOURCE_INFO

	CALL	OPEN_TRANSFER_FILE
	JP	C,FILE_ERROR_EXIT

	CALL	WIFI.UART_FIND
	JP	C,NO_WIFI

	CALL	NETCFG.LOAD
	CALL	NETCFG.APPLY_UART_BAUD
	CALL	WIFI.UART_INIT
	PRINTLN MSG_UART_READY

	LD	HL,CMD_AT
	CALL	SEND_CMD_RECOVER

	LD	HL,CMD_ECHO_OFF
	CALL	SEND_CMD

	; Enable ESP-AT hardware RTS/CTS flow control with the configured baud.
	CALL	WCOMMON.SETUP_UART_FLOW
	AND	A
	JP	NZ,UDP_ERROR_EXIT

	LD	HL,CMD_CIPMUX_0
	CALL	SEND_CMD

	CALL	UDP.CLOSE

	PRINT MSG_CONNECTING
	PRINT HOST_BUFF
	PRINT MSG_COLON
	PRINT PORT_BUFF
	PRINT WCOMMON.LINE_END
	LD	HL,HOST_BUFF
	LD	DE,PORT_BUFF
	LD	IX,LOCAL_PORT
	CALL	UDP.OPEN_LOCAL
	JP	C,UDP_ERROR_EXIT
	LD	A,1
	LD	(UDP_IS_OPEN),A
	CALL	VERIFY_UDP_OPEN
	JP	C,UDP_ERROR_EXIT

	CALL	TRANSFER_TFTP
	JP	C,TRANSFER_ERROR_EXIT

	CALL	UDP.CLOSE
	XOR	A
	LD	(UDP_IS_OPEN),A
	CALL	CLOSE_FILES
	JP	C,FILE_ERROR_EXIT

	PRINT WCOMMON.LINE_END
	PRINTLN MSG_DONE
	LD	B,0
	JP	WCOMMON.EXIT

NO_WIFI
	CALL	CLOSE_FILES_IGNORE
	PRINTLN MSG_WIFI_NOT_FOUND
	LD	B,2
	JP	WCOMMON.EXIT

USAGE
	PRINTLN MSG_USAGE
	LD	B,1
	JP	WCOMMON.EXIT

UDP_ERROR_EXIT
	; Save the inbound error code in A *before* poking CANCELLED — the LD
	; from CANCELLED clobbers A and previously caused every error to print
	; as #0.
	PUSH	AF
	LD	A,(WCOMMON.CANCELLED)
	AND	A
	JR	Z,.NOT_CANCELLED
	POP	AF
	JP	CANCEL_EXIT
.NOT_CANCELLED
	CALL	PRINT_UDP_DEBUG
	LD	A,(UDP_IS_OPEN)
	AND	A
	CALL	NZ,UDP.CLOSE
	XOR	A
	LD	(UDP_IS_OPEN),A
	CALL	CLOSE_FILES_IGNORE
	POP	AF
	ADD	A,'0'
	LD	(MSG_ERROR_NO),A
	PRINTLN MSG_NET_ERROR
	LD	B,3
	JP	WCOMMON.EXIT

PRINT_UDP_DEBUG
	PRINT	MSG_DEBUG
	PRINT	MSG_DEBUG_BLOCK
	LD	HL,(EXPECTED_BLOCK)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_IPD
	LD	HL,(TCP.LAST_IPD_LEN)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_LEFT
	LD	HL,(TCP.PAYLOAD_LEFT)
	CALL	PRINT_HL_DEC
	PRINT	MSG_DEBUG_LSR
	LD	A,(TCP.LAST_LSR)
	CALL	PRINT_A_HEX
	PRINT	MSG_DEBUG_ACC
	LD	A,(TCP.LSR_ACCUM)
	CALL	PRINT_A_HEX
	PRINT	WCOMMON.LINE_END
	RET

PRINT_HL_DEC
	LD	DE,NUM_PRINT_BUFF
	CALL	UTIL.UTOA
	PRINT	NUM_PRINT_BUFF
	RET

PRINT_A_HEX
	LD	C,A
	LD	DE,HEX_PRINT_BUFF
	CALL	UTIL.HEXB
	PRINT	HEX_PRINT_BUFF
	RET

TRANSFER_ERROR_EXIT
	PUSH	AF
	LD	A,(FILE_ERROR_FLAG)
	AND	A
	JR	NZ,.FILE
	POP	AF
	JP	UDP_ERROR_EXIT
.FILE
	POP	AF
	LD	A,(FILE_ERROR_CODE)
	JP	FILE_ERROR_EXIT

FILE_ERROR_EXIT
	PUSH	AF
	CALL	CLOSE_FILES_IGNORE
	POP	AF
	CALL	PRINT_FILE_ERROR
	LD	B,5
	JP	WCOMMON.EXIT

CANCEL_EXIT
	LD	A,(UDP_IS_OPEN)
	AND	A
	CALL	NZ,UDP.CLOSE
	XOR	A
	LD	(UDP_IS_OPEN),A
	CALL	CLOSE_FILES_IGNORE
	PRINT	WCOMMON.LINE_END
	PRINTLN	MSG_CANCELLED
	LD	B,7
	JP	WCOMMON.EXIT

; ------------------------------------------------------
; Parse command line:
;   TFTP.EXE tftp://host[:port]/path FILE
;   TFTP.EXE /PUT FILE tftp://host[:port]/path
;   TFTP.EXE tftp://host[:port]/path PUT FILE
; ------------------------------------------------------
PARSE_CMD_LINE
	XOR	A
	LD	(TRANSFER_MODE),A
	LD	HL,0x8080
	LD	A,(HL)
	AND	A
	JP	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,ARG1_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	CALL	SKIP_SPACES
	JP	C,.ERR
	LD	DE,ARG2_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	CALL	SKIP_SPACES
	JR	C,.NO_ARG3
	LD	DE,ARG3_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JP	C,.ERR
	JR	.CLASSIFY
.NO_ARG3
	XOR	A
	LD	(ARG3_BUFF),A
.CLASSIFY
	CALL	IS_ARG1_PUT
	JR	NC,.PUT_FIRST
	CALL	IS_ARG2_PUT
	JR	NC,.URL_PUT_FILE
	LD	A,(ARG2_BUFF)
	AND	A
	JP	Z,.ERR
	LD	HL,ARG1_BUFF
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	JP	C,.ERR
	LD	HL,ARG2_BUFF
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	RET	NC
	JR	.ERR
.URL_PUT_FILE
	LD	A,(ARG3_BUFF)
	AND	A
	JP	Z,.ERR
	LD	A,1
	LD	(TRANSFER_MODE),A
	LD	HL,ARG1_BUFF
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	JP	C,.ERR
	LD	HL,ARG3_BUFF
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	RET	NC
	JR	.ERR
.PUT_FIRST
	LD	A,(ARG3_BUFF)
	AND	A
	JP	Z,.ERR
	LD	A,1
	LD	(TRANSFER_MODE),A
	LD	HL,ARG2_BUFF
	LD	DE,TFTP_SCHEME
	CALL	UTIL.STARTSWITH
	JR	Z,.PUT_URL_SECOND
	LD	HL,ARG2_BUFF
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	JP	C,.ERR
	LD	HL,ARG3_BUFF
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	RET	NC
	JR	.ERR
.PUT_URL_SECOND
	LD	HL,ARG2_BUFF
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	JP	C,.ERR
	LD	HL,ARG3_BUFF
	LD	DE,OUT_FILE
	LD	C,LOCAL_FILE_SIZE-1
	CALL	COPY_ASCIIZ_LIMIT
	RET	NC
.ERR
	SCF
	RET

IS_ARG1_PUT
	LD	HL,SWITCH_PUT_SLASH
	LD	DE,ARG1_BUFF
	CALL	UTIL.STRCMP
	RET	NC
	LD	HL,SWITCH_PUT
	LD	DE,ARG1_BUFF
	JP	UTIL.STRCMP

IS_ARG2_PUT
	LD	HL,SWITCH_PUT_SLASH
	LD	DE,ARG2_BUFF
	CALL	UTIL.STRCMP
	RET	NC
	LD	HL,SWITCH_PUT
	LD	DE,ARG2_BUFF
	JP	UTIL.STRCMP

SKIP_SPACES
	LD	A,B
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	XOR	A
	LD	(ARG_LEN),A
.NEXT
	LD	A,B
	AND	A
	JR	Z,.END
	LD	A,(HL)
	CP	0x21
	JR	C,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	DE
	INC	HL
	DEC	B
	DEC	C
	LD	A,(ARG_LEN)
	INC	A
	LD	(ARG_LEN),A
	JR	.NEXT
.END
	XOR	A
	LD	(DE),A
	LD	A,(ARG_LEN)
	AND	A
	RET	NZ
.ERR
	SCF
	RET

; ------------------------------------------------------
; Parse URL_BUFF into HOST_BUFF, PORT_BUFF and REMOTE_FILE.
; ------------------------------------------------------
PARSE_URL
	LD	HL,URL_BUFF
	LD	DE,TFTP_SCHEME
	CALL	UTIL.STARTSWITH
	JR	NZ,.ERR
	LD	DE,7
	ADD	HL,DE

	LD	DE,HOST_BUFF
	LD	B,HOST_SIZE-1
.HOST
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	CP	'/'
	JR	Z,.HOST_DONE
	CP	':'
	JR	Z,.PORT
	DJNZ	.HOST_STORE
	JR	.ERR
.HOST_STORE
	LD	(DE),A
	INC	DE
	INC	HL
	JR	.HOST
.HOST_DONE
	XOR	A
	LD	(DE),A
	LD	DE,DEFAULT_PORT
	LD	HL,PORT_BUFF
	CALL	COPY_ASCIIZ_HL
	LD	HL,URL_BUFF
	LD	DE,TFTP_SCHEME
	CALL	UTIL.STARTSWITH
	LD	DE,7
	ADD	HL,DE
.SKIP_TO_PATH
	LD	A,(HL)
	CP	'/'
	JR	Z,.PATH
	AND	A
	JR	Z,.ERR
	INC	HL
	JR	.SKIP_TO_PATH
.PORT
	XOR	A
	LD	(DE),A
	INC	HL
	LD	DE,PORT_BUFF
	LD	B,PORT_SIZE-1
.PORT_LOOP
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	CP	'/'
	JR	Z,.PATH
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	DJNZ	.PORT_STORE
	JR	.ERR
.PORT_STORE
	LD	(DE),A
	INC	DE
	INC	HL
	JR	.PORT_LOOP
.PATH
	XOR	A
	LD	(DE),A
	INC	HL
	LD	A,(HL)
	AND	A
	JR	Z,.ERR
	LD	DE,REMOTE_FILE
	LD	B,REMOTE_FILE_SIZE-1
.PATH_LOOP
	LD	A,(HL)
	AND	A
	JR	Z,.PATH_DONE
	DJNZ	.PATH_STORE
	JR	.ERR
.PATH_STORE
	LD	(DE),A
	INC	DE
	INC	HL
	JR	.PATH_LOOP
.PATH_DONE
	XOR	A
	LD	(DE),A
	AND	A
	RET
.ERR
	SCF
	RET

COPY_ASCIIZ_HL
	LD	A,(DE)
	LD	(HL),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ_HL

COPY_ASCIIZ_LIMIT
	LD	A,(HL)
	AND	A
	JR	Z,.END
	LD	A,C
	AND	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	COPY_ASCIIZ_LIMIT
.END
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET

; ------------------------------------------------------
; TFTP RRQ download.
; ------------------------------------------------------
TRANSFER_TFTP
	LD	A,(TRANSFER_MODE)
	AND	A
	JP	NZ,UPLOAD_WRQ

DOWNLOAD_RRQ
	LD	HL,1
	LD	(EXPECTED_BLOCK),HL
	CALL	BUILD_RRQ_PACKET
	CALL	SEND_PACKET
	RET	C
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A

.RECV_NEXT
	CALL	WCOMMON.CHECK_CANCEL
	JP	C,CANCEL_EXIT
	; Each TFTP DATA is its own UDP datagram. If a previous READ_PAYLOAD
	; timed out mid-datagram, PAYLOAD_LEFT is still non-zero, and the next
	; RECEIVE would skip WAIT_IPD_HEADER and start eating the +IPD header
	; of the retransmitted block as if it were data. Force a fresh +IPD
	; parse on every attempt.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	CALL	RECEIVE_PACKET_RETRY
	RET	C
	CALL	HANDLE_PACKET
	JR	C,.HANDLE_FAIL
	; Reset the corruption-retry counter on every successful packet —
	; transient UART OE / ESP desync should not accumulate against later
	; blocks.
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A
	LD	A,(TRANSFER_DONE)
	AND	A
	JR	Z,.RECV_NEXT
	XOR	A
	RET

.HANDLE_FAIL
	; Server-side TFTP ERROR (opcode 5) is fatal — propagate immediately.
	; Anything else (PROTO_ERR from a desynced +IPD) is recoverable: the
	; TFTP server retransmits last DATA when it sees no ACK, so just
	; resend our last packet (RRQ or ACK_{N-1}) and try to receive again.
	CP	RES_ERROR
	RET	Z
	PUSH	AF
	LD	HL,HANDLE_RETRIES
	DEC	(HL)
	JR	Z,.HANDLE_GIVEUP
	POP	AF
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	.RECV_NEXT
.HANDLE_GIVEUP
	POP	AF
	SCF
	RET

BUILD_RRQ_PACKET
	LD	HL,PACKET_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),1
	INC	HL
	LD	DE,REMOTE_FILE
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,MODE_OCTET
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,PACKET_BUFFER
	AND	A
	SBC	HL,DE
	LD	BC,HL
	LD	(LAST_TX_LEN),BC
	LD	HL,PACKET_BUFFER
	LD	(LAST_TX_PTR),HL
	RET

; ------------------------------------------------------
; TFTP WRQ upload.
; ------------------------------------------------------
UPLOAD_WRQ
	LD	HL,0
	LD	(EXPECTED_BLOCK),HL
	CALL	BUILD_WRQ_PACKET
	CALL	SEND_PACKET
	RET	C
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	CALL	WAIT_ACK_WITH_RETRY
	RET	C

	LD	HL,1
	LD	(EXPECTED_BLOCK),HL
.NEXT_BLOCK
	CALL	WCOMMON.CHECK_CANCEL
	JP	C,CANCEL_EXIT
	CALL	BUILD_DATA_PACKET_FROM_FILE
	RET	C
	CALL	SEND_PACKET
	RET	C
	LD	A,RETRY_LIMIT
	LD	(HANDLE_RETRIES),A
	; See note in DOWNLOAD_RRQ — clear stale PAYLOAD_LEFT before each ACK
	; receive so a previous mid-packet timeout doesn't desync the next
	; +IPD header parse.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	CALL	WAIT_ACK_WITH_RETRY
	RET	C
	CALL	CHECK_UPLOAD_DONE
	RET	Z
	CALL	INC_EXPECTED_BLOCK
	JR	.NEXT_BLOCK

BUILD_WRQ_PACKET
	LD	HL,PACKET_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),2
	INC	HL
	LD	DE,REMOTE_FILE
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,MODE_OCTET
	CALL	APPEND_STR_TO_HL
	INC	HL
	LD	DE,PACKET_BUFFER
	AND	A
	SBC	HL,DE
	LD	BC,HL
	LD	(LAST_TX_LEN),BC
	LD	HL,PACKET_BUFFER
	LD	(LAST_TX_PTR),HL
	RET

BUILD_DATA_PACKET_FROM_FILE
	LD	HL,PACKET_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),3
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	LD	(HL),A
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	LD	(HL),A

	; Pause RX during the slow DSS read so background ESP traffic does
	; not overflow the 16-byte FIFO.
	CALL	WIFI.UART_RX_PAUSE
	LD	A,(IN_FH)
	LD	HL,PACKET_BUFFER+4
	LD	DE,TFTP_DATA_SIZE
	LD	C,DSS_READ_FILE
	RST	DSS
	PUSH	AF,DE
	CALL	WIFI.UART_RX_RESUME
	POP	DE,AF
	JR	C,.FILE_ERROR
	LD	(LAST_DATA_LEN),DE
	LD	BC,DE
	INC	BC
	INC	BC
	INC	BC
	INC	BC
	LD	(LAST_TX_LEN),BC
	LD	HL,PACKET_BUFFER
	LD	(LAST_TX_PTR),HL
	XOR	A
	RET
.FILE_ERROR
	LD	(FILE_ERROR_CODE),A
	LD	A,1
	LD	(FILE_ERROR_FLAG),A
	SCF
	RET

; Wrap RECEIVE_ACK_RETRY with corruption-retry. Caller must initialise
; HANDLE_RETRIES before invoking. On a PROTO_ERR (RES_RS_TIMEOUT from
; HANDLE_ACK_PACKET) we resend the last packet and try again, until the
; corruption budget is exhausted or a fatal/server error occurs.
WAIT_ACK_WITH_RETRY
	; Reset stale PAYLOAD_LEFT (see DOWNLOAD_RRQ note).
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	CALL	RECEIVE_ACK_RETRY
	RET	NC
	CP	RES_RS_TIMEOUT
	RET	NZ							; not a recoverable case
	LD	HL,HANDLE_RETRIES
	DEC	(HL)
	JR	Z,.GIVEUP
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	WAIT_ACK_WITH_RETRY
.GIVEUP
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

RECEIVE_ACK_RETRY
	LD	A,RETRY_LIMIT
	LD	(RETRIES_LEFT),A
.TRY
	; Force fresh +IPD parse on every attempt — see DOWNLOAD_RRQ note.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	LD	HL,PACKET_BUFFER
	LD	BC,TFTP_PACKET_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	UDP.RECEIVE
	JR	NC,.GOT_PACKET
	CP	RES_RS_TIMEOUT
	RET	NZ
	LD	HL,RETRIES_LEFT
	DEC	(HL)
	JR	Z,.TIMEOUT
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	.TRY
.TIMEOUT
	LD	A,RES_RS_TIMEOUT
	SCF
	RET
.GOT_PACKET
	CALL	HANDLE_ACK_PACKET
	RET

HANDLE_ACK_PACKET
	LD	(RECV_LEN),BC
	LD	HL,(RECV_LEN)
	LD	DE,4
	CALL	HL_LT_DE
	JR	C,.PROTO_ERR
	LD	HL,PACKET_BUFFER
	LD	A,(HL)
	AND	A
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(HL)
	CP	4
	JR	Z,.ACK
	CP	5
	JR	Z,.TFTP_ERROR
	JR	.PROTO_ERR
.ACK
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	CP	(HL)
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	CP	(HL)
	JR	NZ,.PROTO_ERR
	XOR	A
	RET
.TFTP_ERROR
	CALL	PRINT_TFTP_ERROR
	LD	A,RES_ERROR
	SCF
	RET
.PROTO_ERR
	; See note in HANDLE_PACKET.PROTO_ERR — RES_RS_TIMEOUT marks this
	; failure as recoverable (corrupt ACK, retransmit DATA may help).
	PRINTLN MSG_PROTO_ERROR
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

CHECK_UPLOAD_DONE
	LD	HL,(LAST_DATA_LEN)
	LD	DE,TFTP_DATA_SIZE
	CALL	HL_LT_DE
	JR	C,.DONE
	PRINT MSG_PROGRESS
	OR	1
	RET
.DONE
	XOR	A
	RET

BUILD_ACK_PACKET
	LD	HL,ACK_BUFFER
	XOR	A
	LD	(HL),A
	INC	HL
	LD	(HL),4
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	LD	(HL),A
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	LD	(HL),A
	LD	HL,ACK_BUFFER
	LD	(LAST_TX_PTR),HL
	LD	BC,4
	LD	(LAST_TX_LEN),BC
	RET

SEND_PACKET
	LD	HL,(LAST_TX_PTR)
	LD	BC,(LAST_TX_LEN)
	JP	UDP.SEND_BUFFER

RECEIVE_PACKET_RETRY
	LD	A,RETRY_LIMIT
	LD	(RETRIES_LEFT),A
.TRY
	; Force fresh +IPD parse on every attempt — see DOWNLOAD_RRQ note.
	LD	HL,0
	LD	(TCP.PAYLOAD_LEFT),HL
	LD	HL,PACKET_BUFFER
	LD	BC,TFTP_PACKET_SIZE
	LD	DE,RECV_TIMEOUT
	CALL	UDP.RECEIVE
	RET	NC
	CP	RES_RS_TIMEOUT
	RET	NZ
	LD	HL,RETRIES_LEFT
	DEC	(HL)
	JR	Z,.TIMEOUT
	PRINTLN MSG_RETRY
	CALL	SEND_PACKET
	RET	C
	JR	.TRY
.TIMEOUT
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

HANDLE_PACKET
	LD	(RECV_LEN),BC
	LD	A,B
	OR	C
	JR	Z,.PROTO_ERR
	LD	HL,(RECV_LEN)
	LD	DE,4
	CALL	HL_LT_DE
	JR	C,.PROTO_ERR

	LD	HL,PACKET_BUFFER
	LD	A,(HL)
	AND	A
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(HL)
	CP	3
	JR	Z,.DATA
	CP	5
	JR	Z,.TFTP_ERROR
	JR	.PROTO_ERR

.DATA
	INC	HL
	LD	A,(EXPECTED_BLOCK+1)
	CP	(HL)
	JR	NZ,.PROTO_ERR
	INC	HL
	LD	A,(EXPECTED_BLOCK)
	CP	(HL)
	JR	NZ,.PROTO_ERR

	; Pause RX while we do the slow DSS write so the ESP cannot push
	; bytes (its own notifications, retransmits, etc.) into a 16-byte
	; FIFO that we are not draining.
	CALL	WIFI.UART_RX_PAUSE
	CALL	WRITE_DATA_PAYLOAD
	PUSH	AF
	CALL	WIFI.UART_RX_RESUME
	POP	AF
	RET	C
	CALL	BUILD_ACK_PACKET
	CALL	SEND_PACKET
	RET	C
	CALL	CHECK_FINAL_BLOCK
	CALL	INC_EXPECTED_BLOCK
	XOR	A
	RET

.TFTP_ERROR
	CALL	PRINT_TFTP_ERROR
	LD	A,RES_ERROR
	SCF
	RET
.PROTO_ERR
	; Use RES_RS_TIMEOUT (not RES_ERROR) so the caller's recovery path
	; can distinguish a corrupt/desynced packet (retransmit may help)
	; from a server-issued TFTP ERROR (fatal).
	PRINTLN MSG_PROTO_ERROR
	LD	A,RES_RS_TIMEOUT
	SCF
	RET

WRITE_DATA_PAYLOAD
	LD	BC,(RECV_LEN)
	DEC	BC
	DEC	BC
	DEC	BC
	DEC	BC
	LD	A,B
	OR	C
	RET	Z
	LD	HL,PACKET_BUFFER+4
	LD	A,(OUT_FH)
	LD	D,B
	LD	E,C
	LD	C,DSS_WRITE
	RST	DSS
	RET

CHECK_FINAL_BLOCK
	LD	HL,(RECV_LEN)
	LD	DE,TFTP_PACKET_SIZE
	CALL	HL_LT_DE
	JR	NC,.MORE
	LD	A,1
	LD	(TRANSFER_DONE),A
	RET
.MORE
	PRINT MSG_PROGRESS
	RET

INC_EXPECTED_BLOCK
	LD	HL,(EXPECTED_BLOCK)
	INC	HL
	LD	(EXPECTED_BLOCK),HL
	RET

HL_LT_DE
	LD	A,H
	CP	D
	RET	NZ
	LD	A,L
	CP	E
	RET

; ------------------------------------------------------
; File helpers.
; ------------------------------------------------------
OPEN_OUTPUT_FILE
	LD	HL,OUT_FILE
	LD	A,FA_ARCHIVE
	LD	C,DSS_CREATE_OVERWRITE
	RST	DSS
	RET	C
	LD	(OUT_FH),A
	RET

OPEN_INPUT_FILE
	LD	HL,OUT_FILE
	LD	A,FM_READ
	LD	C,DSS_OPEN_FILE
	RST	DSS
	RET	C
	LD	(IN_FH),A
	RET

OPEN_TRANSFER_FILE
	LD	A,(TRANSFER_MODE)
	AND	A
	JP	NZ,OPEN_INPUT_FILE
	JP	OPEN_OUTPUT_FILE

CLOSE_OUTPUT_FILE
	LD	A,(OUT_FH)
	CP	NO_HANDLE
	RET	Z
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,NO_HANDLE
	LD	(OUT_FH),A
	RET

CLOSE_INPUT_FILE
	LD	A,(IN_FH)
	CP	NO_HANDLE
	RET	Z
	LD	C,DSS_CLOSE_FILE
	RST	DSS
	LD	A,NO_HANDLE
	LD	(IN_FH),A
	RET

CLOSE_FILES
	CALL	CLOSE_OUTPUT_FILE
	RET	C
	JP	CLOSE_INPUT_FILE

CLOSE_FILES_IGNORE
	CALL	CLOSE_OUTPUT_FILE
	CALL	CLOSE_INPUT_FILE
	RET

PRINT_FILE_ERROR
	PRINT	MSG_FILE_ERROR
	CALL	DSS_ERROR.GET_ERR_MSG
	PRINTLN_HL
	RET

; ------------------------------------------------------
; ESP/UDP command helpers.
; ------------------------------------------------------
SEND_CMD
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	RET	Z
	JP	UDP_ERROR_EXIT

SEND_CMD_RECOVER
	PUSH	HL
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	Z,.OK

	PRINTLN MSG_RESETTING_ESP
	CALL	WIFI.ESP_RESET
	CALL	WIFI.UART_SET_DEFAULT_DIVISOR
	CALL	WIFI.UART_INIT
	POP	HL
	JP	SEND_CMD
.OK
	POP	HL
	RET

VERIFY_UDP_OPEN
	LD	HL,CMD_CIPSTATUS
	LD	DE,WIFI.RS_BUFF
	LD	BC,DEFAULT_TIMEOUT
	CALL	WIFI.UART_TX_CMD
	AND	A
	JR	NZ,.ERR
	LD	HL,WIFI.RS_BUFF
	LD	DE,UDP_STATUS_TOKEN
	CALL	FIND_SUBSTR
	RET	NC
	PRINTLN MSG_UDP_NOT_CONFIRMED
.ERR
	LD	A,RES_ERROR
	SCF
	RET

FIND_SUBSTR
	LD	A,(DE)
	AND	A
	RET	Z
.NEXT_START
	LD	A,(HL)
	AND	A
	JR	Z,.NOT_FOUND
	PUSH	HL
	PUSH	DE
.MATCH
	LD	A,(DE)
	AND	A
	JR	Z,.FOUND_POP
	LD	B,A
	LD	A,(HL)
	AND	A
	JR	Z,.NO_MATCH_POP
	CP	B
	JR	NZ,.NO_MATCH_POP
	INC	HL
	INC	DE
	JR	.MATCH
.FOUND_POP
	POP	DE
	POP	HL
	XOR	A
	RET
.NO_MATCH_POP
	POP	DE
	POP	HL
	INC	HL
	JR	.NEXT_START
.NOT_FOUND
	SCF
	RET

APPEND_STR_TO_HL
	LD	A,(DE)
	LD	(HL),A
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	APPEND_STR_TO_HL

PRINT_SOURCE_INFO
	PRINT MSG_REMOTE
	PRINT URL_BUFF
	PRINT WCOMMON.LINE_END
	LD	A,(TRANSFER_MODE)
	AND	A
	JR	NZ,.INPUT
	PRINT MSG_OUTPUT
	JR	.FILE
.INPUT
	PRINT MSG_INPUT
.FILE
	PRINT OUT_FILE
	PRINT WCOMMON.LINE_END
	RET

PRINT_TFTP_ERROR
	PRINT MSG_TFTP_ERROR
	LD	HL,PACKET_BUFFER+4
	LD	B,80
.NEXT
	LD	A,(HL)
	AND	A
	JR	Z,.DONE
	LD	C,DSS_PUTCHAR
	RST	DSS
	INC	HL
	DJNZ	.NEXT
.DONE
	PRINT WCOMMON.LINE_END
	RET

CLEAR_BSS
	LD	HL,TFTP_BSS_BASE
	LD	DE,TFTP_BSS_BASE+1
	LD	BC,TFTP_BSS_END-TFTP_BSS_BASE-1
	LD	(HL),0
	LDIR
	RET

MSG_START
	DB "TFTP - UDP TFTP client for SprinterESP",0
MSG_USAGE
	DB "Usage: TFTP.EXE tftp://host[:port]/path FILE or TFTP.EXE /PUT FILE tftp://host[:port]/path",0
MSG_REMOTE
	DB "Remote URL: ",0
MSG_OUTPUT
	DB "Output file: ",0
MSG_INPUT
	DB "Input file: ",0
MSG_UART_READY
	DB "UART initialized.",0
MSG_RESETTING_ESP
	DB "ESP did not answer, resetting module.",0
MSG_CONNECTING
	DB "Opening UDP endpoint to ",0
MSG_COLON
	DB ":",0
MSG_RETRY
	DB "Timeout, retrying.",0
MSG_PROGRESS
	DB ".",0
MSG_DONE
	DB "TFTP done.",0
MSG_WIFI_NOT_FOUND
	DB "Sprinter-WiFi not found!",0
MSG_FILE_ERROR
	DB "File error: ",0
MSG_NET_ERROR
	DB "Network/ESP error #"
MSG_ERROR_NO
	DB "n!",0
MSG_PROTO_ERROR
	DB "Unexpected TFTP packet.",0
MSG_TFTP_ERROR
	DB "TFTP error: ",0
MSG_UDP_NOT_CONFIRMED
	DB "UDP socket was not confirmed by ESP status.",0
MSG_CANCELLED
	DB "Cancelled by user.",0
MSG_DEBUG
	DB "TFTP debug:",0
MSG_DEBUG_BLOCK
	DB " block=",0
MSG_DEBUG_IPD
	DB " ipd=",0
MSG_DEBUG_LEFT
	DB " left=",0
MSG_DEBUG_LSR
	DB " lsr=0x",0
MSG_DEBUG_ACC
	DB " lsr_acc=0x",0
HEX_PRINT_BUFF
	DB "xx",0

CMD_AT
	DB "AT",13,10,0
CMD_ECHO_OFF
	DB "ATE0",13,10,0
CMD_CIPMUX_0
	DB "AT+CIPMUX=0",13,10,0
CMD_CIPSTATUS
	DB "AT+CIPSTATUS",13,10,0
UDP_STATUS_TOKEN
	DB "UDP",0

TFTP_SCHEME
	DB "tftp://",0
SWITCH_PUT_SLASH
	DB "/PUT",0
SWITCH_PUT
	DB "PUT",0
DEFAULT_PORT
	DB "69",0
LOCAL_PORT
	DB "1069",0
MODE_OCTET
	DB "octet",0

ARG_LEN		DB 0
OUT_FH		DB NO_HANDLE
IN_FH		DB NO_HANDLE
UDP_IS_OPEN	DB 0
TRANSFER_DONE	DB 0
TRANSFER_MODE	DB 0
FILE_ERROR_FLAG DB 0
FILE_ERROR_CODE DB 0
RETRIES_LEFT	DB 0
HANDLE_RETRIES	DB 0
EXPECTED_BLOCK	DW 1
RECV_LEN	DW 0
LAST_TX_PTR	DW 0
LAST_TX_LEN	DW 0
LAST_DATA_LEN	DW 0

	ENDMODULE

	DEFINE ESP_TCP_BSS_BASE_OVERRIDE
ESP_TCP_BSS_BASE	EQU 0xB000

	INCLUDE "netcfg_lib.asm"
	INCLUDE "wcommon.asm"
	INCLUDE "dss_error.asm"
	INCLUDE "isa.asm"
	INCLUDE "esp_tcp.asm"
	INCLUDE "esp_udp.asm"
	INCLUDE "esplib.asm"

	MODULE MAIN

; Place TFTP buffers AFTER TCP/UDP buffers, not just after NETCFG. The
; ESP_TCP_BSS_BASE override (0xB000) puts TCP/UDP CMD buffers inside the
; TFTP BSS range — HOST_BUFF then overlaps UDP CMD_BUFFER, and
; APPEND_IX_STR(HOST_BUFF) inside UDP.OPEN_LOCAL falls into an infinite
; loop reading from the buffer it's currently writing to (the bug that
; corrupted memory with repeated "AT+CIPSTART=\"UDP\",\"192.168.1." pattern).
TFTP_BSS_BASE	EQU UDP.UDP_BSS_END
NUM_PRINT_BUFF	EQU TFTP_BSS_BASE
ARG1_BUFF	EQU NUM_PRINT_BUFF + 8
ARG2_BUFF	EQU ARG1_BUFF + URL_SIZE
ARG3_BUFF	EQU ARG2_BUFF + URL_SIZE
URL_BUFF	EQU ARG3_BUFF + URL_SIZE
HOST_BUFF	EQU URL_BUFF + URL_SIZE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
REMOTE_FILE	EQU PORT_BUFF + PORT_SIZE
OUT_FILE	EQU REMOTE_FILE + REMOTE_FILE_SIZE
PACKET_BUFFER	EQU OUT_FILE + LOCAL_FILE_SIZE
ACK_BUFFER	EQU PACKET_BUFFER + TFTP_PACKET_SIZE
TFTP_BSS_END	EQU ACK_BUFFER + 4

	ENDMODULE

	END MAIN.START
