; Host-side regression harness for the actual ZM.SEND_ZRINIT and
; ZM.SEND_SUBPACKET routines. Run through tools/test-zmodem.sh.

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

WIN2_BASE	EQU 0x8000
CAPTURE		EQU 0xC100
TEST_RESULT	EQU 0xC000

	ORG 0x4000

TEST_START
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	XOR	A
	LD	(TEST_RESULT),A

	CALL	ZM.SEND_ZRINIT
	LD	HL,TEST_DATA
	LD	BC,TEST_DATA_LEN
	LD	A,ZCRCW
	CALL	ZM.SEND_SUBPACKET

	LD	HL,CAPTURE
	LD	DE,EXPECTED
	LD	B,EXPECTED_LEN
.compare
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare
	LD	HL,(TEST.CAPTURE_PTR)
	LD	DE,CAPTURE+EXPECTED_LEN
	OR	A
	SBC	HL,DE
	JP	NZ,.failed

	; Decode the same lrzsz-compatible header through the real receive path.
	LD	HL,EXPECTED
	LD	(ZM.SRC_PTR),HL
	LD	HL,EXPECTED_HDR_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZRINIT
	JP	NZ,.failed
	LD	HL,(ZM.HDR_P0)
	LD	DE,0x2000
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,(ZM.HDR_P2)
	LD	DE,0x4100
	OR	A
	SBC	HL,DE
	JP	NZ,.failed

	; Decode and CRC-check the generated "hello" subpacket.
	LD	HL,EXPECTED+EXPECTED_HDR_LEN
	LD	(ZM.SRC_PTR),HL
	LD	HL,EXPECTED_SUB_LEN
	LD	(ZM.SRC_CNT),HL
	XOR	A
	LD	(ZM.SP_TO_FILE),A
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	CP	ZCRCW
	JP	NZ,.failed
	LD	A,D
	OR	A
	JP	NZ,.failed
	LD	A,E
	CP	5
	JP	NZ,.failed

	; Telnet doubles a literal IAC. The Zmodem decoder must collapse FF FF to
	; one data byte before checking the standard CRC 0x2039.
	LD	HL,IAC_SUBPACKET
	LD	(ZM.SRC_PTR),HL
	LD	HL,IAC_SUBPACKET_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	LD	A,(ZM.DATA_BUF)
	CP	0xFF
	JP	NZ,.failed
	LD	HL,BAD_CRC_SUBPACKET
	LD	(ZM.SRC_PTR),HL
	LD	HL,BAD_CRC_SUBPACKET_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_SUBPACKET
	JP	NC,.failed

	; Upload metadata keeps only the basename and emits a decimal file size.
	LD	HL,LOCAL_PATH
	LD	DE,ZM.FNAME
	LD	BC,LOCAL_PATH_LEN
	LDIR
	LD	HL,1234
	LD	(ZM.FILE_SIZE),HL
	LD	HL,0
	LD	(ZM.FILE_SIZE+2),HL
	CALL	ZM.BUILD_FILE_INFO
	LD	HL,(ZM.INFO_LEN)
	LD	DE,EXPECTED_INFO_LEN
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,ZM.DATA_BUF
	LD	DE,EXPECTED_INFO
	LD	B,EXPECTED_INFO_LEN
.compare_info
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare_info
	JR	TEST_DONE
.failed
	LD	A,1
	LD	(TEST_RESULT),A
TEST_DONE
	NOP

TEST_DATA
	DB "hello"
TEST_DATA_LEN	EQU $-TEST_DATA

; ZRINIT(type=1, rxlen=0x2000, flags=CANFDX|ESCCTL), CRC=0x9A48.
; "hello" + ZCRCW, CRC=0x7975.
EXPECTED
	DB 0x2A,0x2A,0x18,'B'
	DB "01002000419a48"
	DB 0x0D,0x8A,0x11
EXPECTED_HDR_LEN	EQU $-EXPECTED
	DB "hello",0x18,'k',0x79,0x75,0x11
EXPECTED_SUB_LEN	EQU $-EXPECTED-EXPECTED_HDR_LEN
EXPECTED_LEN	EQU $-EXPECTED

IAC_SUBPACKET
	DB 0xFF,0xFF,0x18,'k',0x20,0x39
IAC_SUBPACKET_LEN	EQU $-IAC_SUBPACKET
BAD_CRC_SUBPACKET
	DB 0xFF,0xFF,0x18,'k',0x20,0x38
BAD_CRC_SUBPACKET_LEN	EQU $-BAD_CRC_SUBPACKET

LOCAL_PATH
	DB "C:\\DIR\\TEST.BIN",0
LOCAL_PATH_LEN	EQU $-LOCAL_PATH
EXPECTED_INFO
	DB "TEST.BIN",0,"0000001234 0 0 0 1 0",0
EXPECTED_INFO_LEN	EQU $-EXPECTED_INFO

	MODULE MAIN
RX_DRAIN_WAIT
RX_DRAIN
	SCF
	RET
	ENDMODULE

	MODULE WIFI
UART_RX_PAUSE
	RET
UART_RX_RESUME
	RET
UART_TX_BUFFER
	LD	DE,(TEST.CAPTURE_PTR)
	LDIR
	LD	(TEST.CAPTURE_PTR),DE
	OR	A
	RET
	ENDMODULE

	MODULE UTIL
DELAY
	RET
	ENDMODULE

	MODULE WCOMMON
CANCELLED	DB 0
LINE_END	DB 13,10,0
	ENDMODULE

	MODULE TCP
SEND_BUFFER
SEND_BUFFER_NO_WAIT
	LD	DE,(TEST.CAPTURE_PTR)
	LDIR
	LD	(TEST.CAPTURE_PTR),DE
	OR	A
	RET
RECEIVE
	SCF
	RET
	ENDMODULE

	MODULE TEST
CAPTURE_PTR	DW CAPTURE
	ENDMODULE

	INCLUDE "zmodem.asm"

	END TEST_START
