; Host-side regression harness for the actual ZM.SEND_ZRINIT and
; ZM.SEND_SUBPACKET routines. Run through tools/test-zmodem.sh.

	DEVICE NOSLOT64K
	DEFINE ZM_TEST_REFILL

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"

WIN2_BASE	EQU 0x8000
REG_FCR		EQU 0
CAPTURE		EQU 0xC100
TEST_RESULT	EQU 0xC000

	ORG 0x4000

TEST_START
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	XOR	A
	LD	(TEST_RESULT),A

	CALL	ZM.SEND_ZRINIT
	LD	HL,TEST_DATA
	LD	BC,TEST_DATA_LEN
	LD	A,ZCRCW
	CALL	ZM.SEND_SUBPACKET

	LD	HL,CAPTURE
	LD	DE,EXPECTED
	LD	B,EXPECTED_LEN
.compare
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare
	LD	HL,(TEST.CAPTURE_PTR)
	LD	DE,CAPTURE+EXPECTED_LEN
	OR	A
	SBC	HL,DE
	JP	NZ,.failed

	; Decode the same lrzsz-compatible header through the real receive path.
	LD	HL,EXPECTED
	LD	(ZM.SRC_PTR),HL
	LD	HL,EXPECTED_HDR_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZRINIT
	JP	NZ,.failed
	LD	HL,(ZM.HDR_P0)
	LD	DE,0x2000
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,(ZM.HDR_P2)
	LD	DE,0x4100
	OR	A
	SBC	HL,DE
	JP	NZ,.failed

	; Independent lrzsz 0.12.20 vector emitted by `rz`: unlike the generated
	; frame above, this catches a shared encoder/decoder CRC mistake.
	LD	HL,LRZSZ_ZRINIT
	LD	(ZM.SRC_PTR),HL
	LD	HL,LRZSZ_ZRINIT_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZRINIT
	JP	NZ,.failed
	LD	A,(ZM.HDR_P3)
	CP	0x23
	JP	NZ,.failed

	; Actual raw-TCP VERSION transfer emitted by lrzsz `sz -o` after accepting
	; our ZRINIT/ZRPOS. It covers ZFILE, metadata, ZDATA, data and ZEOF parsing.
	LD	HL,LRZSZ_VERSION_STREAM
	LD	(ZM.SRC_PTR),HL
	LD	HL,LRZSZ_VERSION_STREAM_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZFILE
	JP	NZ,.failed
	XOR	A
	LD	(ZM.SP_TO_FILE),A
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	LD	HL,ZM.DATA_BUF
	LD	DE,LRZSZ_VERSION_NAME
	LD	B,LRZSZ_VERSION_NAME_LEN
.compare_lrzsz_name
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare_lrzsz_name
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZDATA
	JP	NZ,.failed
	XOR	A
	LD	(ZM.SP_TO_FILE),A
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	CP	ZCRCE
	JP	NZ,.failed
	LD	A,D
	OR	A
	JP	NZ,.failed
	LD	A,E
	CP	4
	JP	NZ,.failed
	LD	HL,ZM.DATA_BUF
	LD	DE,LRZSZ_VERSION_DATA
	LD	B,4
.compare_lrzsz_data
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare_lrzsz_data
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZEOF
	JP	NZ,.failed
	LD	A,(ZM.HDR_P0)
	CP	4
	JP	NZ,.failed

	; Exact ZFILE+metadata captured from the user's 192.168.1.36:2323 server.
	; Its metadata CRC is A4B0 and must pass before any DSS file operation.
	LD	HL,REMOTE_README_STREAM
	LD	(ZM.SRC_PTR),HL
	LD	HL,REMOTE_README_STREAM_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZFILE
	JP	NZ,.failed
	XOR	A
	LD	(ZM.SP_TO_FILE),A
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	LD	HL,(ZM.SP_CRC)
	LD	DE,0xA4B0
	OR	A
	SBC	HL,DE
	JP	NZ,.failed

	; Repeat the remote frame one byte per FILL and deliberately clobber IX in
	; every refill, matching DSS/ISA behavior on hardware.
	XOR	A
	LD	(MAIN.TN_PEER_SEEN),A
	LD	HL,0
	LD	(ZM.SRC_CNT),HL
	LD	HL,REMOTE_README_STREAM
	LD	(TEST.REFILL_PTR),HL
	LD	HL,REMOTE_README_STREAM_LEN
	LD	(TEST.REFILL_LEFT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZFILE
	JP	NZ,.failed
	XOR	A
	LD	(ZM.SP_TO_FILE),A
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	LD	HL,(ZM.SP_CRC)
	LD	DE,0xA4B0
	OR	A
	SBC	HL,DE
	JP	NZ,.failed

	; Decode and CRC-check the generated "hello" subpacket.
	LD	HL,EXPECTED+EXPECTED_HDR_LEN
	LD	(ZM.SRC_PTR),HL
	LD	HL,EXPECTED_SUB_LEN
	LD	(ZM.SRC_CNT),HL
	XOR	A
	LD	(ZM.SP_TO_FILE),A
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	CP	ZCRCW
	JP	NZ,.failed
	LD	A,D
	OR	A
	JP	NZ,.failed
	LD	A,E
	CP	5
	JP	NZ,.failed

	; Telnet doubles a literal IAC. The Zmodem decoder must collapse FF FF to
	; one data byte before checking the standard CRC 0xDE32. First decode an
	; ordinary binary header through the Telnet branch: CP 0xFF must not leak
	; Carry for every non-IAC byte.
	LD	A,1
	LD	(MAIN.TN_PEER_SEEN),A
	LD	HL,LRZSZ_VERSION_STREAM
	LD	(ZM.SRC_PTR),HL
	LD	HL,LRZSZ_VERSION_STREAM_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_HEADER
	JP	C,.failed
	CP	ZFILE
	JP	NZ,.failed
	LD	HL,IAC_SUBPACKET
	LD	(ZM.SRC_PTR),HL
	LD	HL,IAC_SUBPACKET_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_SUBPACKET
	JP	C,.failed
	LD	A,(ZM.DATA_BUF)
	CP	0xFF
	JP	NZ,.failed
	LD	HL,BAD_CRC_SUBPACKET
	LD	(ZM.SRC_PTR),HL
	LD	HL,BAD_CRC_SUBPACKET_LEN
	LD	(ZM.SRC_CNT),HL
	CALL	ZM.RECV_SUBPACKET
	JP	NC,.failed

	; Upload metadata keeps only the basename and emits a decimal file size.
	LD	HL,LOCAL_PATH
	LD	DE,ZM.FNAME
	LD	BC,LOCAL_PATH_LEN
	LDIR
	LD	HL,1234
	LD	(ZM.FILE_SIZE),HL
	LD	HL,0
	LD	(ZM.FILE_SIZE+2),HL
	CALL	ZM.BUILD_FILE_INFO
	LD	HL,(ZM.INFO_LEN)
	LD	DE,EXPECTED_INFO_LEN
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,ZM.DATA_BUF
	LD	DE,EXPECTED_INFO
	LD	B,EXPECTED_INFO_LEN
.compare_info
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare_info

	; Progress is based on the confirmed 32-bit byte position. 0x00123456
	; bytes becomes 0x0000048D = 1165 whole kilobytes without leading zeroes.
	LD	HL,0x3456
	LD	(ZM.FPOS),HL
	LD	HL,0x0012
	LD	(ZM.FPOS+2),HL
	CALL	ZM.PREP_PROGRESS_KB
	LD	HL,(ZM.U32_WORK)
	LD	DE,0x048D
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,(ZM.U32_WORK+2)
	LD	A,H
	OR	L
	JP	NZ,.failed
	CALL	ZM.FORMAT_PROGRESS_KB
	LD	HL,ZM.PROGRESS_NUM
	LD	DE,EXPECTED_PROGRESS
	LD	B,EXPECTED_PROGRESS_LEN
.compare_progress
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare_progress

	; Ymodem block 0: SOH, block/complement, 128 data bytes and XMODEM CRC.
	; CRC16/XMODEM("123456789" + 119 zeroes) is independently known as D053.
	LD	HL,ZM.DATA_BUF
	LD	DE,ZM.DATA_BUF+1
	LD	BC,YM_META_SIZE-1
	LD	(HL),0
	LDIR
	LD	HL,YM_TEST_DATA
	LD	DE,ZM.DATA_BUF
	LD	BC,YM_TEST_DATA_LEN
	LDIR
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	XOR	A
	LD	(MAIN.TN_PEER_SEEN),A
	LD	(YM.TX_BLOCK),A
	LD	A,YM_SOH
	LD	DE,YM_META_SIZE
	CALL	YM.SEND_CURRENT_PACKET
	JP	C,.failed
	LD	HL,(TEST.CAPTURE_PTR)
	LD	DE,CAPTURE+133
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	A,(CAPTURE)
	CP	YM_SOH
	JP	NZ,.failed
	LD	A,(CAPTURE+1)
	OR	A
	JP	NZ,.failed
	LD	A,(CAPTURE+2)
	CP	0xFF
	JP	NZ,.failed
	LD	A,(CAPTURE+131)
	CP	0xD0
	JP	NZ,.failed
	LD	A,(CAPTURE+132)
	CP	0x53
	JP	NZ,.failed
	LD	HL,CAPTURE
	LD	(ZM.SRC_PTR),HL
	LD	HL,133
	LD	(ZM.SRC_CNT),HL
	CALL	YM.RECV_PACKET
	JP	C,.failed
	OR	A
	JP	NZ,.failed
	LD	A,(YM.RX_BLOCK)
	OR	A
	JP	NZ,.failed
	LD	HL,(YM.RX_LENGTH)
	LD	DE,YM_META_SIZE
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,ZM.DATA_BUF
	LD	DE,YM_TEST_DATA
	LD	B,YM_TEST_DATA_LEN
.compare_ym_data
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.failed
	INC	HL
	INC	DE
	DJNZ	.compare_ym_data

	; Block 15 contains the control-valued sequence byte 0x0F. Verify that the
	; real encoder emits 0F/F0 unchanged and that the decoder accepts it; some
	; remote terminal bridges incorrectly consume Ctrl-O unless their PTY is raw.
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	XOR	A
	LD	(MAIN.TN_PEER_SEEN),A
	LD	A,15
	LD	(YM.TX_BLOCK),A
	LD	A,YM_SOH
	LD	DE,YM_META_SIZE
	CALL	YM.SEND_CURRENT_PACKET
	JP	C,.failed
	LD	A,(CAPTURE+1)
	CP	0x0F
	JP	NZ,.failed
	LD	A,(CAPTURE+2)
	CP	0xF0
	JP	NZ,.failed
	LD	HL,CAPTURE
	LD	(ZM.SRC_PTR),HL
	LD	HL,133
	LD	(ZM.SRC_CNT),HL
	CALL	YM.RECV_PACKET
	JP	C,.failed
	LD	A,(YM.RX_BLOCK)
	CP	15
	JP	NZ,.failed

	; A real Telnet peer doubles IAC in both the block complement and payload.
	LD	HL,ZM.DATA_BUF
	LD	DE,ZM.DATA_BUF+1
	LD	BC,YM_META_SIZE-1
	LD	(HL),0xFF
	LDIR
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	LD	A,1
	LD	(MAIN.TN_PEER_SEEN),A
	XOR	A
	LD	(YM.TX_BLOCK),A
	LD	A,YM_SOH
	LD	DE,YM_META_SIZE
	CALL	YM.SEND_CURRENT_PACKET
	JP	C,.failed
	LD	HL,(TEST.CAPTURE_PTR)
	LD	DE,CAPTURE
	OR	A
	SBC	HL,DE
	LD	(ZM.SRC_CNT),HL
	LD	HL,CAPTURE
	LD	(ZM.SRC_PTR),HL
	CALL	YM.RECV_PACKET
	JP	C,.failed
	LD	A,(ZM.DATA_BUF)
	CP	0xFF
	JP	NZ,.failed

	; Standard Ymodem metadata begins with basename NUL and decimal byte size.
	LD	HL,YM_TEST_META
	LD	DE,ZM.DATA_BUF
	LD	BC,YM_TEST_META_LEN
	LDIR
	CALL	YM.PARSE_FILE_SIZE
	LD	A,(YM.SIZE_KNOWN)
	OR	A
	JP	Z,.failed
	LD	HL,(YM.FILE_LEFT)
	LD	DE,2030
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,(YM.FILE_LEFT+2)
	LD	A,H
	OR	L
	JP	NZ,.failed

	; Explicit receiver starts must put the correct mode request on the wire.
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	LD	A,1
	LD	(YM.G_MODE),A
	CALL	YM.SEND_RX_REQUEST
	LD	A,(CAPTURE)
	CP	YM_G_REQ
	JP	NZ,.failed
	LD	HL,(TEST.CAPTURE_PTR)
	LD	DE,CAPTURE+1
	OR	A
	SBC	HL,DE
	JP	NZ,.failed
	LD	HL,CAPTURE
	LD	(TEST.CAPTURE_PTR),HL
	XOR	A
	LD	(YM.G_MODE),A
	CALL	YM.SEND_RX_REQUEST
	LD	A,(CAPTURE)
	CP	YM_CRC_REQ
	JP	NZ,.failed
	JR	TEST_DONE
.failed
	LD	A,1
	LD	(TEST_RESULT),A
TEST_DONE
	NOP

TEST_DATA
	DB "hello"
TEST_DATA_LEN	EQU $-TEST_DATA

; ZRINIT(type=1, rxlen=0x2000, flags=CANFDX|ESCCTL), CRC=0x7472.
; "hello" + ZCRCW, CRC=0x56E2.
EXPECTED
	DB 0x2A,0x2A,0x18,'B'
	DB "01002000417472"
	DB 0x0D,0x8A,0x11
EXPECTED_HDR_LEN	EQU $-EXPECTED
	DB "hello",0x18,'k',0x56,0xE2,0x11
EXPECTED_SUB_LEN	EQU $-EXPECTED-EXPECTED_HDR_LEN
EXPECTED_LEN	EQU $-EXPECTED

LRZSZ_ZRINIT
	DB 0x2A,0x2A,0x18,'B',"0100000023be50",0x0D,0x8A,0x11
LRZSZ_ZRINIT_LEN	EQU $-LRZSZ_ZRINIT

LRZSZ_VERSION_STREAM
	DB 0x2A,0x18,'A'
	DB 0x18,0x44,0x18,0x40,0x18,0x40,0x18,0x40,0x18,0x40
	DB 0x18,0xC9,0x18,0x46
	DB "VERSION",0x18,0x40
	DB "4 15210261416 100644 0 1 4",0x18,0x40
	DB 0x18,'k',0x18,0xDA,0x76,0x11
	DB 0x2A,0x18,'A'
	DB 0x18,0x4A,0x18,0x40,0x18,0x40,0x18,0x40,0x18,0x40
	DB 0x46,0xAE
	DB "0.1",0x18,0x4A,0x18,'h',0x69,0x18,0x4A
	DB 0x2A,0x18,'A'
	DB 0x18,0x4B,0x18,0x44,0x18,0x40,0x18,0x40,0x18,0x40
	DB 0x26,0x18,0x4E
LRZSZ_VERSION_STREAM_LEN	EQU $-LRZSZ_VERSION_STREAM
LRZSZ_VERSION_NAME
	DB "VERSION",0
LRZSZ_VERSION_NAME_LEN	EQU $-LRZSZ_VERSION_NAME
LRZSZ_VERSION_DATA
	DB "0.1",0x0A

REMOTE_README_STREAM
	DB 0x2A,0x18,'A'
	DB 0x18,0x44,0x18,0x40,0x18,0x40,0x18,0x40,0x18,0x40
	DB 0x18,0xC9,0x18,0x46
	DB "readme.md",0x18,0x40
	DB "2030 15174033562 100644 0 1 2030",0x18,0x40
	DB 0x18,'k',0xA4,0xB0,0x11
REMOTE_README_STREAM_LEN	EQU $-REMOTE_README_STREAM

IAC_SUBPACKET
	DB 0xFF,0xFF,0x18,'k',0xDE,0x32
IAC_SUBPACKET_LEN	EQU $-IAC_SUBPACKET
BAD_CRC_SUBPACKET
	DB 0xFF,0xFF,0x18,'k',0xDE,0x33
BAD_CRC_SUBPACKET_LEN	EQU $-BAD_CRC_SUBPACKET

LOCAL_PATH
	DB "C:\\DIR\\TEST.BIN",0
LOCAL_PATH_LEN	EQU $-LOCAL_PATH
EXPECTED_INFO
	DB "TEST.BIN",0,"0000001234 0 0 0 1 0",0
EXPECTED_INFO_LEN	EQU $-EXPECTED_INFO
EXPECTED_PROGRESS
	DB "1165",0
EXPECTED_PROGRESS_LEN	EQU $-EXPECTED_PROGRESS
YM_TEST_DATA
	DB "123456789"
YM_TEST_DATA_LEN	EQU $-YM_TEST_DATA
YM_TEST_META
	DB "readme.md",0,"2030 15174033562 100644",0
YM_TEST_META_LEN	EQU $-YM_TEST_META

	MODULE MAIN
TN_PEER_SEEN
	DB 0
YM_C_PENDING
	DB 0
OUTPUT_BYTE
	RET
TEST_FILL
	LD	HL,(TEST.REFILL_LEFT)
	LD	A,H
	OR	L
	JR	Z,.empty
	DEC	HL
	LD	(TEST.REFILL_LEFT),HL
	LD	HL,(TEST.REFILL_PTR)
	LD	A,(HL)
	INC	HL
	LD	(TEST.REFILL_PTR),HL
	LD	(ZM.RXBUF),A
	LD	HL,ZM.RXBUF
	LD	(ZM.SRC_PTR),HL
	LD	HL,1
	LD	(ZM.SRC_CNT),HL
	LD	IX,0xDEAD		; prove decoder state does not live in IX
	OR	A
	RET
.empty
	SCF
	RET
RX_DRAIN_WAIT
RX_DRAIN
	SCF
	RET
	ENDMODULE

	MODULE WIFI
UART_WRITE
	RET
UART_RX_PAUSE
	RET
UART_RX_RESUME
	RET
UART_TX_BUFFER
	LD	DE,(TEST.CAPTURE_PTR)
	LDIR
	LD	(TEST.CAPTURE_PTR),DE
	OR	A
	RET
	ENDMODULE

	MODULE UTIL
DELAY
	RET
	ENDMODULE

	MODULE WCOMMON
CANCELLED	DB 0
LINE_END	DB 13,10,0
	ENDMODULE

	MODULE TCP
SEND_BUFFER
SEND_BUFFER_NO_WAIT
	LD	DE,(TEST.CAPTURE_PTR)
	LDIR
	LD	(TEST.CAPTURE_PTR),DE
	OR	A
	RET
RECEIVE
	SCF
	RET
	ENDMODULE

	MODULE TEST
CAPTURE_PTR	DW CAPTURE
REFILL_PTR	DW 0
REFILL_LEFT	DW 0
	ENDMODULE

	INCLUDE "zmodem.asm"
	INCLUDE "ymodem.asm"

	END TEST_START
